const RECENT_KEY = "alysum-emoji-recent";
const RECENT_MAX = 27;

/** Emojis that get a looping sparkle / pulse animation in reactions (Discord-style). */
export const LOUNGE_ANIMATED_EMOJIS = new Set([
    "✨", "⭐", "🌟", "💫", "💖", "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "💔",
    "🔥", "😂", "🤣", "😭", "🥹", "🎉", "🎊", "💯", "👀", "🫶", "🙌", "👏", "💀", "😍",
    "🥳", "⚡", "💥", "🌈", "🎆", "💃", "🕺", "🫡", "🤯", "😱", "🤩", "💕", "💞", "💓"
]);

export function isLoungeAnimatedEmoji(emoji) {
    return LOUNGE_ANIMATED_EMOJIS.has(String(emoji || "").trim());
}

const EMOJI_CATEGORIES = [
    {
        id: "smileys",
        icon: "😀",
        label: "Smileys",
        items: [
            ["😀", "grinning smile happy"],
            ["😃", "smiley happy"],
            ["😄", "smile grin"],
            ["😁", "beaming grin"],
            ["😆", "laugh squint"],
            ["😅", "sweat smile nervous"],
            ["🤣", "rofl laugh"],
            ["😂", "joy tears laugh"],
            ["🙂", "slight smile"],
            ["🙃", "upside down"],
            ["😉", "wink"],
            ["😊", "blush smile"],
            ["😇", "innocent angel"],
            ["🥰", "love hearts smile"],
            ["😍", "heart eyes love"],
            ["🤩", "star struck wow"],
            ["😘", "kiss heart"],
            ["😗", "kiss"],
            ["😚", "kiss closed eyes"],
            ["😙", "kiss smile"],
            ["🥲", "smile tear"],
            ["😋", "yum delicious"],
            ["😛", "tongue"],
            ["😜", "wink tongue crazy"],
            ["🤪", "zany crazy"],
            ["😝", "squint tongue"],
            ["🤑", "money mouth"],
            ["🤗", "hug"],
            ["🤭", "giggle hand"],
            ["🤫", "shush quiet"],
            ["🤔", "thinking hmm"],
            ["🤐", "zipper mouth"],
            ["🤨", "raised eyebrow"],
            ["😐", "neutral"],
            ["😑", "expressionless"],
            ["😶", "no mouth"],
            ["😏", "smirk"],
            ["😒", "unamused"],
            ["🙄", "eye roll"],
            ["😬", "grimace"],
            ["😮‍💨", "exhale sigh"],
            ["🤥", "lying pinocchio"],
            ["😌", "relieved"],
            ["😔", "pensive sad"],
            ["😪", "sleepy"],
            ["🤤", "drool"],
            ["😴", "sleep zzz"],
            ["😷", "mask sick"],
            ["🤒", "sick thermometer"],
            ["🤕", "injured bandage"],
            ["🤢", "nauseated sick"],
            ["🤮", "vomit sick"],
            ["🤧", "sneeze"],
            ["🥵", "hot sweat"],
            ["🥶", "cold freeze"],
            ["🥴", "woozy drunk"],
            ["😵", "dizzy"],
            ["🤯", "mind blown"],
            ["🤠", "cowboy"],
            ["🥳", "party celebrate"],
            ["🥸", "disguise"],
            ["😎", "cool sunglasses"],
            ["🤓", "nerd glasses"],
            ["🧐", "monocle"],
            ["😕", "confused"],
            ["😟", "worried"],
            ["🙁", "slight frown sad"],
            ["☹️", "frown sad"],
            ["😮", "open mouth surprise"],
            ["😯", "hushed surprise"],
            ["😲", "astonished wow"],
            ["😳", "flushed embarrassed"],
            ["🥺", "pleading puppy eyes"],
            ["😦", "frown open mouth"],
            ["😧", "anguished"],
            ["😨", "fear scared"],
            ["😰", "anxious sweat"],
            ["😥", "sad relieved sweat"],
            ["😢", "cry tear sad"],
            ["😭", "sob cry loud"],
            ["😱", "scream fear"],
            ["😖", "confounded"],
            ["😣", "persevere struggle"],
            ["😞", "disappointed sad"],
            ["😓", "downcast sweat"],
            ["😩", "weary tired"],
            ["😫", "tired exhausted"],
            ["🥱", "yawn tired"],
            ["😤", "triumph steam"],
            ["😡", "angry mad pout"],
            ["😠", "angry mad"],
            ["🤬", "swearing angry"],
            ["😈", "smiling devil"],
            ["👿", "angry devil"],
            ["💀", "skull dead"],
            ["☠️", "skull crossbones"],
            ["💩", "poop"],
            ["🤡", "clown"],
            ["👹", "ogre monster"],
            ["👺", "goblin"],
            ["👻", "ghost"],
            ["👽", "alien ufo"],
            ["👾", "space invader"],
            ["🤖", "robot"],
            ["😺", "cat smile"],
            ["😸", "cat grin"],
            ["😹", "cat laugh"],
            ["😻", "cat heart eyes"],
            ["😼", "cat smirk"],
            ["😽", "cat kiss"],
            ["🙀", "cat scream"],
            ["😿", "cat cry"],
            ["😾", "cat pout"]
        ]
    },
    {
        id: "people",
        icon: "👋",
        label: "People",
        items: [
            ["👋", "wave hello bye"],
            ["🤚", "raised back hand"],
            ["🖐️", "hand fingers"],
            ["✋", "raised hand stop"],
            ["🖖", "vulcan spock"],
            ["👌", "ok perfect"],
            ["🤌", "pinched fingers"],
            ["🤏", "pinch small"],
            ["✌️", "peace victory"],
            ["🤞", "crossed fingers luck"],
            ["🤟", "love you"],
            ["🤘", "rock horns"],
            ["🤙", "call me shaka"],
            ["👈", "point left"],
            ["👉", "point right"],
            ["👆", "point up"],
            ["👇", "point down"],
            ["☝️", "index up"],
            ["👍", "thumbs up yes"],
            ["👎", "thumbs down no"],
            ["✊", "fist bump"],
            ["👊", "punch fist"],
            ["🤛", "left fist bump"],
            ["🤜", "right fist bump"],
            ["👏", "clap applause"],
            ["🙌", "raised hands celebrate"],
            ["👐", "open hands"],
            ["🤲", "palms up"],
            ["🤝", "handshake deal"],
            ["🙏", "pray thanks please"],
            ["✍️", "writing pen"],
            ["💅", "nail polish"],
            ["🤳", "selfie"],
            ["💪", "flex strong muscle"],
            ["🦾", "mechanical arm"],
            ["🦿", "mechanical leg"],
            ["🦵", "leg"],
            ["🦶", "foot"],
            ["👂", "ear listen"],
            ["🦻", "ear hearing aid"],
            ["👃", "nose"],
            ["🧠", "brain smart"],
            ["🫀", "heart organ"],
            ["🫁", "lungs"],
            ["🦷", "tooth"],
            ["🦴", "bone"],
            ["👀", "eyes look"],
            ["👁️", "eye"],
            ["👅", "tongue"],
            ["👄", "lips mouth kiss"],
            ["👶", "baby"],
            ["🧒", "child kid"],
            ["👦", "boy"],
            ["👧", "girl"],
            ["🧑", "person adult"],
            ["👱", "blond person"],
            ["👨", "man"],
            ["👩", "woman"],
            ["🧓", "older person"],
            ["👴", "old man"],
            ["👵", "old woman"],
            ["🙍", "frown person"],
            ["🙎", "pout person"],
            ["🙅", "no gesture"],
            ["🙆", "ok gesture"],
            ["💁", "information sassy"],
            ["🙋", "hand raise question"],
            ["🧏", "deaf person"],
            ["🙇", "bow sorry"],
            ["🤦", "facepalm"],
            ["🤷", "shrug idk"],
            ["👮", "police officer"],
            ["🕵️", "detective spy"],
            ["💂", "guard"],
            ["🥷", "ninja"],
            ["👷", "construction worker"],
            ["🤴", "prince"],
            ["👸", "princess"],
            ["👳", "person turban"],
            ["👲", "person cap"],
            ["🧕", "hijab"],
            ["🤵", "tuxedo"],
            ["👰", "bride wedding"],
            ["🤰", "pregnant"],
            ["🤱", "breastfeeding"],
            ["👼", "baby angel"],
            ["🎅", "santa christmas"],
            ["🤶", "mrs claus"],
            ["🦸", "superhero"],
            ["🦹", "supervillain"],
            ["🧙", "wizard mage"],
            ["🧚", "fairy"],
            ["🧛", "vampire"],
            ["🧜", "merperson mermaid"],
            ["🧝", "elf"],
            ["🧞", "genie"],
            ["🧟", "zombie"],
            ["💆", "massage"],
            ["💇", "haircut"],
            ["🚶", "walk walking"],
            ["🧍", "standing"],
            ["🧎", "kneeling"],
            ["🏃", "run running"],
            ["💃", "dance woman"],
            ["🕺", "dance man"],
            ["🧖", "sauna steam"],
            ["🧗", "climbing"],
            ["🤺", "fencing"],
            ["🏇", "horse racing"],
            ["⛷️", "ski"],
            ["🏂", "snowboard"],
            ["🏌️", "golf"],
            ["🏄", "surf"],
            ["🚣", "row boat"],
            ["🏊", "swim"],
            ["⛹️", "basketball person"],
            ["🏋️", "weight lift gym"],
            ["🚴", "bike cycling"],
            ["🚵", "mountain bike"],
            ["🤸", "cartwheel"],
            ["🤼", "wrestling"],
            ["🤽", "water polo"],
            ["🤾", "handball"],
            ["🤹", "juggling"],
            ["🧘", "yoga meditate"],
            ["🛀", "bath"],
            ["🛌", "sleep bed"],
            ["👫", "couple hold hands"],
            ["👭", "women holding hands"],
            ["👬", "men holding hands"],
            ["💑", "couple heart love"],
            ["👪", "family"],
            ["🗣️", "speaking head"],
            ["👤", "silhouette person"],
            ["👥", "silhouettes people"]
        ]
    },
    {
        id: "nature",
        icon: "🐻",
        label: "Nature",
        items: [
            ["🐶", "dog puppy"],
            ["🐱", "cat kitty"],
            ["🐭", "mouse"],
            ["🐹", "hamster"],
            ["🐰", "rabbit bunny"],
            ["🦊", "fox"],
            ["🐻", "bear"],
            ["🐼", "panda"],
            ["🐻‍❄️", "polar bear"],
            ["🐨", "koala"],
            ["🐯", "tiger"],
            ["🦁", "lion"],
            ["🐮", "cow"],
            ["🐷", "pig"],
            ["🐸", "frog"],
            ["🐵", "monkey"],
            ["🙈", "see no evil monkey"],
            ["🙉", "hear no evil monkey"],
            ["🙊", "speak no evil monkey"],
            ["🐒", "monkey"],
            ["🐔", "chicken"],
            ["🐧", "penguin"],
            ["🐦", "bird"],
            ["🐤", "baby chick"],
            ["🐣", "hatching chick"],
            ["🐥", "front chick"],
            ["🦆", "duck"],
            ["🦅", "eagle"],
            ["🦉", "owl"],
            ["🦇", "bat"],
            ["🐺", "wolf"],
            ["🐗", "boar"],
            ["🐴", "horse"],
            ["🦄", "unicorn"],
            ["🐝", "bee honey"],
            ["🪱", "worm"],
            ["🐛", "bug caterpillar"],
            ["🦋", "butterfly"],
            ["🐌", "snail"],
            ["🐞", "ladybug"],
            ["🐜", "ant"],
            ["🪰", "fly"],
            ["🪲", "beetle"],
            ["🪳", "cockroach"],
            ["🦟", "mosquito"],
            ["🦗", "cricket"],
            ["🕷️", "spider"],
            ["🦂", "scorpion"],
            ["🐢", "turtle"],
            ["🐍", "snake"],
            ["🦎", "lizard"],
            ["🦖", "t rex dinosaur"],
            ["🦕", "sauropod dinosaur"],
            ["🐙", "octopus"],
            ["🦑", "squid"],
            ["🦐", "shrimp"],
            ["🦞", "lobster"],
            ["🦀", "crab"],
            ["🐡", "blowfish"],
            ["🐠", "tropical fish"],
            ["🐟", "fish"],
            ["🐬", "dolphin"],
            ["🐳", "whale spout"],
            ["🐋", "whale"],
            ["🦈", "shark"],
            ["🐊", "crocodile"],
            ["🐅", "tiger"],
            ["🐆", "leopard"],
            ["🦓", "zebra"],
            ["🦍", "gorilla"],
            ["🦧", "orangutan"],
            ["🐘", "elephant"],
            ["🦛", "hippo"],
            ["🦏", "rhino"],
            ["🐪", "camel"],
            ["🐫", "two hump camel"],
            ["🦒", "giraffe"],
            ["🦘", "kangaroo"],
            ["🦬", "bison"],
            ["🐃", "water buffalo"],
            ["🐂", "ox"],
            ["🐄", "cow"],
            ["🐎", "racehorse"],
            ["🐖", "pig"],
            ["🐏", "ram sheep"],
            ["🐑", "ewe sheep"],
            ["🦙", "llama alpaca"],
            ["🐐", "goat"],
            ["🦌", "deer"],
            ["🐕", "dog"],
            ["🐩", "poodle dog"],
            ["🦮", "guide dog"],
            ["🐈", "cat"],
            ["🐓", "rooster"],
            ["🦃", "turkey"],
            ["🦤", "dodo"],
            ["🦚", "peacock"],
            ["🦜", "parrot"],
            ["🦢", "swan"],
            ["🕊️", "dove peace"],
            ["🐇", "rabbit"],
            ["🦝", "raccoon"],
            ["🦨", "skunk"],
            ["🦡", "badger"],
            ["🦫", "beaver"],
            ["🦦", "otter"],
            ["🦥", "sloth"],
            ["🐁", "mouse"],
            ["🐀", "rat"],
            ["🐿️", "chipmunk squirrel"],
            ["🦔", "hedgehog"],
            ["🐾", "paw prints"],
            ["🐉", "dragon"],
            ["🐲", "dragon face"],
            ["🌵", "cactus"],
            ["🎄", "christmas tree"],
            ["🌲", "evergreen tree"],
            ["🌳", "deciduous tree"],
            ["🌴", "palm tree"],
            ["🌱", "seedling plant"],
            ["🌿", "herb leaf"],
            ["☘️", "shamrock"],
            ["🍀", "four leaf clover luck"],
            ["🍁", "maple leaf fall"],
            ["🍂", "fallen leaf autumn"],
            ["🍃", "leaf wind"],
            ["🪴", "potted plant"],
            ["🌾", "sheaf rice wheat"],
            ["🌺", "hibiscus flower"],
            ["🌻", "sunflower"],
            ["🌹", "rose flower love"],
            ["🥀", "wilted flower"],
            ["🌷", "tulip"],
            ["🌼", "blossom"],
            ["🌸", "cherry blossom sakura"],
            ["💐", "bouquet flowers"],
            ["🍄", "mushroom"],
            ["🌎", "earth globe americas"],
            ["🌍", "earth globe europe africa"],
            ["🌏", "earth globe asia"],
            ["🌕", "full moon"],
            ["🌖", "waning gibbous moon"],
            ["🌗", "last quarter moon"],
            ["🌘", "waning crescent moon"],
            ["🌑", "new moon"],
            ["🌒", "waxing crescent moon"],
            ["🌓", "first quarter moon"],
            ["🌔", "waxing gibbous moon"],
            ["🌙", "crescent moon night"],
            ["🌚", "new moon face"],
            ["🌛", "first quarter moon face"],
            ["🌜", "last quarter moon face"],
            ["☀️", "sun sunny"],
            ["🌝", "full moon face"],
            ["⭐", "star"],
            ["🌟", "glowing star sparkle"],
            ["💫", "dizzy star"],
            ["✨", "sparkles shine"],
            ["☄️", "comet"],
            ["🌠", "shooting star wish"],
            ["🌈", "rainbow"],
            ["☁️", "cloud"],
            ["⛅", "sun behind cloud"],
            ["⛈️", "storm cloud lightning"],
            ["🌤️", "sun small cloud"],
            ["🌥️", "sun big cloud"],
            ["🌦️", "sun rain cloud"],
            ["🌧️", "rain cloud"],
            ["🌨️", "snow cloud"],
            ["🌩️", "lightning cloud"],
            ["🌪️", "tornado"],
            ["🌫️", "fog"],
            ["🌊", "wave ocean water"],
            ["💧", "droplet water"],
            ["💦", "sweat droplets"],
            ["☔", "umbrella rain"],
            ["🔥", "fire flame hot"],
            ["❄️", "snowflake cold"],
            ["🌬️", "wind face"],
            ["🌀", "cyclone hurricane"],
            ["🌁", "foggy"],
            ["🌋", "volcano"],
            ["🏔️", "snow mountain"],
            ["⛰️", "mountain"]
        ]
    },
    {
        id: "food",
        icon: "🍔",
        label: "Food",
        items: [
            ["🍏", "green apple"],
            ["🍎", "red apple"],
            ["🍐", "pear"],
            ["🍊", "orange tangerine"],
            ["🍋", "lemon"],
            ["🍌", "banana"],
            ["🍉", "watermelon"],
            ["🍇", "grapes"],
            ["🍓", "strawberry"],
            ["🫐", "blueberries"],
            ["🍈", "melon"],
            ["🍒", "cherries"],
            ["🍑", "peach"],
            ["🥭", "mango"],
            ["🍍", "pineapple"],
            ["🥥", "coconut"],
            ["🥝", "kiwi"],
            ["🍅", "tomato"],
            ["🍆", "eggplant"],
            ["🥑", "avocado"],
            ["🥦", "broccoli"],
            ["🥬", "leafy green"],
            ["🥒", "cucumber pickle"],
            ["🌶️", "hot pepper spicy"],
            ["🫑", "bell pepper"],
            ["🌽", "corn"],
            ["🥕", "carrot"],
            ["🫒", "olive"],
            ["🧄", "garlic"],
            ["🧅", "onion"],
            ["🥔", "potato"],
            ["🍠", "sweet potato"],
            ["🥐", "croissant"],
            ["🥯", "bagel"],
            ["🍞", "bread toast"],
            ["🥖", "baguette bread"],
            ["🥨", "pretzel"],
            ["🧀", "cheese"],
            ["🥚", "egg"],
            ["🍳", "cooking egg fried"],
            ["🧈", "butter"],
            ["🥞", "pancakes"],
            ["🧇", "waffle"],
            ["🥓", "bacon"],
            ["🥩", "steak meat"],
            ["🍗", "poultry leg chicken"],
            ["🍖", "meat bone"],
            ["🌭", "hot dog"],
            ["🍔", "burger hamburger"],
            ["🍟", "fries french"],
            ["🍕", "pizza"],
            ["🫓", "flatbread"],
            ["🥪", "sandwich"],
            ["🥙", "stuffed flatbread"],
            ["🧆", "falafel"],
            ["🌮", "taco"],
            ["🌯", "burrito"],
            ["🫔", "tamale"],
            ["🥗", "salad green"],
            ["🥘", "paella shallow pan"],
            ["🫕", "fondue pot"],
            ["🍝", "spaghetti pasta"],
            ["🍜", "ramen noodles bowl"],
            ["🍲", "pot food stew"],
            ["🍛", "curry rice"],
            ["🍣", "sushi"],
            ["🍱", "bento box"],
            ["🥟", "dumpling"],
            ["🦪", "oyster"],
            ["🍤", "fried shrimp"],
            ["🍙", "rice ball onigiri"],
            ["🍚", "cooked rice"],
            ["🍘", "rice cracker"],
            ["🍥", "fish cake"],
            ["🥠", "fortune cookie"],
            ["🥮", "moon cake"],
            ["🍢", "oden skewer"],
            ["🍡", "dango"],
            ["🍧", "shaved ice"],
            ["🍨", "ice cream"],
            ["🍦", "soft ice cream"],
            ["🥧", "pie"],
            ["🧁", "cupcake"],
            ["🍰", "cake slice birthday"],
            ["🎂", "birthday cake"],
            ["🍮", "custard pudding"],
            ["🍭", "lollipop candy"],
            ["🍬", "candy sweet"],
            ["🍫", "chocolate bar"],
            ["🍿", "popcorn movie"],
            ["🍩", "donut doughnut"],
            ["🍪", "cookie"],
            ["🌰", "chestnut"],
            ["🥜", "peanuts"],
            ["🍯", "honey pot"],
            ["🥛", "milk glass"],
            ["🍼", "baby bottle"],
            ["☕", "coffee hot"],
            ["🫖", "teapot tea"],
            ["🍵", "tea cup"],
            ["🧃", "juice box"],
            ["🥤", "cup straw soda"],
            ["🧋", "bubble tea boba"],
            ["🍶", "sake bottle"],
            ["🍺", "beer mug"],
            ["🍻", "beers cheers clink"],
            ["🥂", "champagne clink toast"],
            ["🍷", "wine glass"],
            ["🥃", "tumbler whiskey"],
            ["🍸", "cocktail martini"],
            ["🍹", "tropical drink"],
            ["🧉", "mate"],
            ["🍾", "champagne bottle pop"]
        ]
    },
    {
        id: "travel",
        icon: "✈️",
        label: "Travel",
        items: [
            ["🚗", "car red"],
            ["🚕", "taxi"],
            ["🚙", "suv car"],
            ["🚌", "bus"],
            ["🚎", "trolleybus"],
            ["🏎️", "race car fast"],
            ["🚓", "police car"],
            ["🚑", "ambulance"],
            ["🚒", "fire engine truck"],
            ["🚐", "minibus van"],
            ["🛻", "pickup truck"],
            ["🚚", "delivery truck"],
            ["🚛", "articulated lorry"],
            ["🚜", "tractor farm"],
            ["🏍️", "motorcycle"],
            ["🛵", "scooter moped"],
            ["🛺", "auto rickshaw"],
            ["🚲", "bicycle bike"],
            ["🛴", "kick scooter"],
            ["🛹", "skateboard"],
            ["🛼", "roller skate"],
            ["🚏", "bus stop"],
            ["🛣️", "motorway highway"],
            ["🛤️", "railway track"],
            ["⛽", "fuel pump gas"],
            ["🚨", "police light siren"],
            ["🚥", "traffic light horizontal"],
            ["🚦", "traffic light vertical"],
            ["🛑", "stop sign"],
            ["🚧", "construction"],
            ["⚓", "anchor ship boat"],
            ["⛵", "sailboat boat"],
            ["🛶", "canoe"],
            ["🚤", "speedboat"],
            ["🛳️", "passenger ship cruise"],
            ["⛴️", "ferry"],
            ["🛥️", "motor boat"],
            ["🚢", "ship"],
            ["✈️", "airplane plane fly"],
            ["🛩️", "small airplane"],
            ["🛫", "departure airplane"],
            ["🛬", "arrival airplane landing"],
            ["🪂", "parachute"],
            ["💺", "seat chair"],
            ["🚁", "helicopter"],
            ["🚟", "suspension railway"],
            ["🚠", "mountain cableway"],
            ["🚡", "aerial tramway"],
            ["🛰️", "satellite space"],
            ["🚀", "rocket space launch"],
            ["🛸", "flying saucer ufo"],
            ["🧳", "luggage suitcase travel"],
            ["⌛", "hourglass time"],
            ["⏳", "hourglass flowing time"],
            ["⌚", "watch time"],
            ["⏰", "alarm clock"],
            ["⏱️", "stopwatch"],
            ["⏲️", "timer clock"],
            ["🕰️", "mantelpiece clock"],
            ["🌍", "globe world earth travel"],
            ["🗺️", "world map"],
            ["🗾", "map japan"],
            ["🏔️", "mountain snow"],
            ["⛰️", "mountain"],
            ["🌋", "volcano"],
            ["🗻", "mount fuji"],
            ["🏕️", "camping tent"],
            ["🏖️", "beach umbrella"],
            ["🏜️", "desert"],
            ["🏝️", "desert island"],
            ["🏞️", "national park"],
            ["🏟️", "stadium"],
            ["🏛️", "classical building museum"],
            ["🏗️", "building construction"],
            ["🧱", "brick wall"],
            ["🏘️", "houses"],
            ["🏚️", "derelict house"],
            ["🏠", "house home"],
            ["🏡", "house garden home"],
            ["🏢", "office building"],
            ["🏣", "post office"],
            ["🏤", "post office european"],
            ["🏥", "hospital"],
            ["🏦", "bank"],
            ["🏨", "hotel"],
            ["🏩", "love hotel"],
            ["🏪", "convenience store"],
            ["🏫", "school"],
            ["🏬", "department store mall"],
            ["🏭", "factory"],
            ["🏯", "japanese castle"],
            ["🏰", "castle"],
            ["💒", "wedding chapel"],
            ["🗼", "tokyo tower"],
            ["🗽", "statue liberty"],
            ["⛪", "church"],
            ["🕌", "mosque"],
            ["🛕", "hindu temple"],
            ["🕍", "synagogue"],
            ["⛩️", "shrine torii"],
            ["🕋", "kaaba"],
            ["⛲", "fountain"],
            ["⛺", "tent camping"],
            ["🌁", "foggy bridge"],
            ["🌃", "night stars city"],
            ["🏙️", "cityscape skyline"],
            ["🌄", "sunrise mountains"],
            ["🌅", "sunrise"],
            ["🌆", "city dusk sunset"],
            ["🌇", "sunset city"],
            ["🌉", "bridge night"],
            ["♨️", "hot springs onsen"],
            ["🎠", "carousel horse"],
            ["🎡", "ferris wheel"],
            ["🎢", "roller coaster"],
            ["💈", "barber pole"],
            ["🎪", "circus tent"]
        ]
    },
    {
        id: "activities",
        icon: "⚽",
        label: "Activities",
        items: [
            ["⚽", "soccer football ball"],
            ["🏀", "basketball"],
            ["🏈", "football american"],
            ["⚾", "baseball"],
            ["🥎", "softball"],
            ["🎾", "tennis"],
            ["🏐", "volleyball"],
            ["🏉", "rugby football"],
            ["🥏", "flying disc frisbee"],
            ["🎱", "pool 8 ball billiards"],
            ["🪀", "yo yo"],
            ["🏓", "ping pong table tennis"],
            ["🏸", "badminton"],
            ["🏒", "ice hockey"],
            ["🏑", "field hockey"],
            ["🥍", "lacrosse"],
            ["🏏", "cricket"],
            ["🪃", "boomerang"],
            ["🥅", "goal net"],
            ["⛳", "golf flag hole"],
            ["🪁", "kite fly"],
            ["🏹", "bow arrow archery"],
            ["🎣", "fishing pole"],
            ["🤿", "diving mask snorkel"],
            ["🥊", "boxing glove"],
            ["🥋", "martial arts karate"],
            ["🎽", "running shirt"],
            ["🛹", "skateboard"],
            ["🛼", "roller skate"],
            ["🛷", "sled"],
            ["⛸️", "ice skate"],
            ["🥌", "curling stone"],
            ["🎿", "skis ski"],
            ["⛷️", "skier ski"],
            ["🏂", "snowboarder"],
            ["🪂", "parachute skydive"],
            ["🏋️", "weight lifter gym"],
            ["🤼", "wrestlers"],
            ["🤸", "person cartwheel gymnastics"],
            ["⛹️", "basketball person bounce"],
            ["🤺", "fencer fencing sword"],
            ["🤾", "handball"],
            ["🏌️", "golfer golf"],
            ["🏇", "horse racing jockey"],
            ["🧘", "yoga lotus meditate"],
            ["🏄", "surfer surf wave"],
            ["🏊", "swimmer swim"],
            ["🤽", "water polo"],
            ["🚣", "rowboat row"],
            ["🧗", "climber rock climbing"],
            ["🚴", "bicyclist bike"],
            ["🚵", "mountain biker"],
            ["🎯", "dart target bullseye"],
            ["🎮", "video game controller gaming"],
            ["🕹️", "joystick arcade"],
            ["🎰", "slot machine casino"],
            ["🎲", "dice game roll"],
            ["🧩", "puzzle piece jigsaw"],
            ["♟️", "chess pawn"],
            ["🎭", "performing arts theater drama"],
            ["🎨", "artist palette art paint"],
            ["🧵", "thread sewing"],
            ["🪡", "sewing needle"],
            ["🧶", "yarn knitting"],
            ["🎼", "musical score sheet music"],
            ["🎤", "microphone karaoke sing"],
            ["🎧", "headphones music listen"],
            ["🎷", "saxophone jazz"],
            ["🎸", "guitar rock"],
            ["🎹", "piano keyboard music"],
            ["🎺", "trumpet brass"],
            ["🎻", "violin classical"],
            ["🥁", "drum beat"],
            ["🪘", "long drum"],
            ["🎬", "clapper board movie film"],
            ["🏆", "trophy win champion"],
            ["🥇", "gold medal first place"],
            ["🥈", "silver medal second"],
            ["🥉", "bronze medal third"],
            ["🏅", "sports medal"],
            ["🎖️", "military medal"],
            ["🏵️", "rosette"],
            ["🎗️", "reminder ribbon"],
            ["🎫", "ticket event"],
            ["🎟️", "admission tickets"],
            ["🎪", "circus tent show"],
            ["🤹", "juggling"],
            ["🎠", "carousel"],
            ["🎡", "ferris wheel fair"],
            ["🎢", "roller coaster amusement"],
            ["🎆", "fireworks celebrate"],
            ["🎇", "sparkler fireworks"],
            ["🧨", "firecracker"],
            ["✨", "sparkles magic"],
            ["🎈", "balloon party"],
            ["🎉", "party popper celebrate tada"],
            ["🎊", "confetti ball party"],
            ["🎁", "gift present wrapped"],
            ["🎀", "ribbon bow"],
            ["🎂", "birthday cake party"],
            ["🎄", "christmas tree holiday"],
            ["🎃", "jack o lantern halloween pumpkin"],
            ["🎑", "moon viewing"],
            ["🎐", "wind chime"],
            ["🎏", "carp streamer"],
            ["🎎", "dolls japanese"],
            ["🎍", "pine decoration"],
            ["🎋", "tanabata tree wish"],
            ["🎊", "confetti"],
            ["🧧", "red envelope lucky money"],
            ["🎴", "flower playing cards hanafuda"],
            ["🀄", "mahjong red dragon"],
            ["🃏", "joker card"],
            ["🎴", "playing cards"],
            ["♠️", "spades suit card"],
            ["♥️", "hearts suit card love"],
            ["♦️", "diamonds suit card"],
            ["♣️", "clubs suit card"]
        ]
    },
    {
        id: "objects",
        icon: "💡",
        label: "Objects",
        items: [
            ["⌚", "watch time"],
            ["📱", "mobile phone iphone"],
            ["📲", "mobile arrow phone call"],
            ["💻", "laptop computer"],
            ["⌨️", "keyboard typing"],
            ["🖥️", "desktop computer monitor"],
            ["🖨️", "printer"],
            ["🖱️", "computer mouse click"],
            ["🖲️", "trackball"],
            ["💽", "minidisc"],
            ["💾", "floppy disk save"],
            ["💿", "optical disk cd"],
            ["📀", "dvd disk"],
            ["📼", "vhs tape"],
            ["📷", "camera photo"],
            ["📸", "camera flash photo"],
            ["📹", "video camera film"],
            ["🎥", "movie camera film"],
            ["📽️", "film projector cinema"],
            ["🎞️", "film frames movie"],
            ["📞", "telephone phone call"],
            ["☎️", "telephone old phone"],
            ["📟", "pager"],
            ["📠", "fax machine"],
            ["📺", "television tv"],
            ["📻", "radio"],
            ["🎙️", "studio microphone podcast"],
            ["🎚️", "level slider audio"],
            ["🎛️", "control knobs"],
            ["🧭", "compass navigation"],
            ["⏱️", "stopwatch timer"],
            ["⏲️", "timer clock"],
            ["⏰", "alarm clock wake"],
            ["🕰️", "mantel clock"],
            ["⌛", "hourglass done time"],
            ["⏳", "hourglass not done waiting"],
            ["📡", "satellite antenna signal"],
            ["🔋", "battery power"],
            ["🔌", "electric plug power"],
            ["💡", "light bulb idea bright"],
            ["🔦", "flashlight torch"],
            ["🕯️", "candle light"],
            ["🪔", "diya lamp"],
            ["🧯", "fire extinguisher"],
            ["🛢️", "oil drum"],
            ["💸", "money wings flying cash"],
            ["💵", "dollar bill money"],
            ["💴", "yen bill money"],
            ["💶", "euro bill money"],
            ["💷", "pound bill money"],
            ["🪙", "coin money"],
            ["💰", "money bag rich"],
            ["💳", "credit card payment"],
            ["💎", "gem diamond jewel"],
            ["⚖️", "balance scale justice"],
            ["🪜", "ladder"],
            ["🧰", "toolbox tools"],
            ["🪛", "screwdriver tool"],
            ["🔧", "wrench tool fix"],
            ["🔨", "hammer tool build"],
            ["⚒️", "hammer pick tools"],
            ["🛠️", "hammer wrench tools"],
            ["⛏️", "pick mining"],
            ["🪓", "axe chop wood"],
            ["🔩", "nut bolt screw"],
            ["⚙️", "gear settings cog"],
            ["🧱", "brick wall build"],
            ["⛓️", "chains link"],
            ["🧲", "magnet attract"],
            ["🔫", "water pistol gun"],
            ["💣", "bomb boom"],
            ["🧨", "firecracker boom"],
            ["🪓", "axe"],
            ["🔪", "kitchen knife cut"],
            ["🗡️", "dagger sword"],
            ["⚔️", "crossed swords battle"],
            ["🛡️", "shield protect defense"],
            ["🚬", "cigarette smoke"],
            ["⚰️", "coffin death"],
            ["🪦", "headstone grave"],
            ["⚱️", "funeral urn"],
            ["🏺", "amphora vase pottery"],
            ["🔮", "crystal ball magic fortune"],
            ["📿", "prayer beads"],
            ["🧿", "nazar amulet evil eye"],
            ["💈", "barber pole haircut"],
            ["⚗️", "alembic chemistry"],
            ["🔭", "telescope stars space"],
            ["🔬", "microscope science lab"],
            ["🕳️", "hole"],
            ["🩹", "adhesive bandage bandaid"],
            ["🩺", "stethoscope doctor medical"],
            ["💊", "pill medicine drug"],
            ["💉", "syringe vaccine shot"],
            ["🩸", "drop blood"],
            ["🧬", "dna genetics science"],
            ["🦠", "microbe virus germ"],
            ["🧫", "petri dish lab"],
            ["🧪", "test tube science experiment"],
            ["🌡️", "thermometer temperature"],
            ["🧹", "broom clean sweep"],
            ["🪠", "plunger"],
            ["🧺", "basket laundry"],
            ["🧻", "roll paper toilet"],
            ["🪣", "bucket pail"],
            ["🧼", "soap wash clean"],
            ["🪥", "toothbrush teeth"],
            ["🧽", "sponge clean"],
            ["🧴", "lotion bottle"],
            ["🛎️", "bellhop bell service"],
            ["🔑", "key unlock"],
            ["🗝️", "old key antique"],
            ["🚪", "door enter exit"],
            ["🪑", "chair seat sit"],
            ["🛋️", "couch sofa"],
            ["🛏️", "bed sleep"],
            ["🛌", "person bed sleep"],
            ["🧸", "teddy bear plush toy"],
            ["🖼️", "framed picture art"],
            ["🪞", "mirror reflection"],
            ["🪟", "window"],
            ["🛍️", "shopping bags mall"],
            ["🛒", "shopping cart grocery"],
            ["🎁", "wrapped gift present"],
            ["🎈", "balloon party"],
            ["🎏", "carp streamer"],
            ["🎀", "ribbon bow gift"],
            ["🎊", "confetti ball"],
            ["🎉", "party popper celebrate"],
            ["🎎", "japanese dolls"],
            ["🏮", "red paper lantern"],
            ["🎐", "wind chime"],
            ["🧧", "red envelope"],
            ["✉️", "envelope mail letter"],
            ["📩", "envelope arrow email"],
            ["📨", "incoming envelope mail"],
            ["📧", "email e mail"],
            ["💌", "love letter valentine"],
            ["📥", "inbox tray download"],
            ["📤", "outbox tray upload send"],
            ["📦", "package box delivery"],
            ["🏷️", "label tag price"],
            ["🪧", "placard sign protest"],
            ["📪", "closed mailbox"],
            ["📫", "mailbox raised flag"],
            ["📬", "open mailbox raised flag"],
            ["📭", "open mailbox lowered flag"],
            ["📮", "postbox mail send"],
            ["📝", "memo note write pencil"],
            ["📄", "page document paper"],
            ["📃", "page curl document"],
            ["📑", "bookmark tabs"],
            ["🧾", "receipt bill"],
            ["📊", "bar chart graph stats"],
            ["📈", "chart increasing trend up"],
            ["📉", "chart decreasing trend down"],
            ["🗒️", "spiral notepad notes"],
            ["🗓️", "spiral calendar"],
            ["📆", "tear off calendar date"],
            ["📅", "calendar date schedule"],
            ["🗑️", "wastebasket trash delete"],
            ["📇", "card index rolodex"],
            ["📁", "file folder"],
            ["📂", "open file folder"],
            ["🗂️", "card index dividers"],
            ["📋", "clipboard copy paste"],
            ["📌", "pushpin pin tack"],
            ["📍", "round pushpin location map pin"],
            ["🖇️", "linked paperclips"],
            ["📎", "paperclip attach"],
            ["🖊️", "pen write ink"],
            ["🖋️", "fountain pen write"],
            ["✒️", "black nib pen"],
            ["🖌️", "paintbrush art"],
            ["🖍️", "crayon draw color"],
            ["📝", "pencil memo write notes"],
            ["✏️", "pencil write edit"],
            ["🔍", "magnifying glass left search find"],
            ["🔎", "magnifying glass right search zoom"],
            ["🔏", "locked pen privacy"],
            ["🔐", "locked key secure"],
            ["🔒", "locked secure private"],
            ["🔓", "unlocked open"],
            ["📚", "books read library study"],
            ["📖", "open book read"],
            ["📕", "closed book red"],
            ["📗", "closed book green"],
            ["📘", "closed book blue"],
            ["📙", "closed book orange"],
            ["📓", "notebook"],
            ["📒", "ledger notebook"],
            ["📃", "page curl"],
            ["📜", "scroll ancient document"],
            ["📰", "newspaper news"],
            ["🗞️", "rolled up newspaper"],
            ["📑", "bookmark tabs mark"],
            ["🔖", "bookmark save mark"],
            ["🏷️", "label tag"],
            ["💼", "briefcase work business"],
            ["📁", "folder files"],
            ["🗃️", "card file box"],
            ["🗄️", "file cabinet storage"]
        ]
    },
    {
        id: "symbols",
        icon: "❤️",
        label: "Symbols",
        items: [
            ["❤️", "red heart love"],
            ["🧡", "orange heart"],
            ["💛", "yellow heart"],
            ["💚", "green heart"],
            ["💙", "blue heart"],
            ["💜", "purple heart"],
            ["🖤", "black heart"],
            ["🤍", "white heart"],
            ["🤎", "brown heart"],
            ["💔", "broken heart sad"],
            ["❣️", "heart exclamation"],
            ["💕", "two hearts love"],
            ["💞", "revolving hearts"],
            ["💓", "beating heart pulse"],
            ["💗", "growing heart"],
            ["💖", "sparkling heart"],
            ["💘", "heart arrow cupid love"],
            ["💝", "heart ribbon gift"],
            ["💟", "heart decoration"],
            ["☮️", "peace symbol"],
            ["✝️", "latin cross"],
            ["☪️", "star crescent islam"],
            ["🕉️", "om hindu"],
            ["☸️", "wheel dharma"],
            ["✡️", "star david"],
            ["🔯", "dotted six pointed star"],
            ["🕎", "menorah hanukkah"],
            ["☯️", "yin yang balance"],
            ["☦️", "orthodox cross"],
            ["🛐", "place worship pray"],
            ["⛎", "ophiuchus zodiac"],
            ["♈", "aries zodiac"],
            ["♉", "taurus zodiac"],
            ["♊", "gemini zodiac"],
            ["♋", "cancer zodiac"],
            ["♌", "leo zodiac"],
            ["♍", "virgo zodiac"],
            ["♎", "libra zodiac"],
            ["♏", "scorpio zodiac"],
            ["♐", "sagittarius zodiac"],
            ["♑", "capricorn zodiac"],
            ["♒", "aquarius zodiac"],
            ["♓", "pisces zodiac"],
            ["🆔", "id button"],
            ["⚛️", "atom symbol science"],
            ["🉑", "accept button ok"],
            ["☢️", "radioactive danger"],
            ["☣️", "biohazard danger"],
            ["📴", "mobile phone off"],
            ["📳", "vibration mode phone"],
            ["🈶", "not free charge japanese"],
            ["🈚", "free japanese"],
            ["🈸", "application japanese"],
            ["🈺", "open business japanese"],
            ["🈷️", "monthly amount japanese"],
            ["✴️", "eight pointed star"],
            ["🆚", "vs versus"],
            ["💮", "white flower japanese"],
            ["🉐", "bargain japanese deal"],
            ["㊙️", "secret japanese"],
            ["㊗️", "congratulations japanese"],
            ["🈴", "passing grade japanese"],
            ["🈵", "no vacancy full japanese"],
            ["🈹", "discount japanese sale"],
            ["🈲", "prohibited japanese no"],
            ["🅰️", "a button blood type"],
            ["🅱️", "b button blood type"],
            ["🆎", "ab button blood type"],
            ["🆑", "cl button clear"],
            ["🅾️", "o button blood type"],
            ["🆘", "sos help emergency"],
            ["❌", "cross mark wrong no x"],
            ["⭕", "hollow red circle o yes"],
            ["🛑", "stop sign octagonal"],
            ["⛔", "no entry prohibited"],
            ["📛", "name badge"],
            ["🚫", "prohibited no banned"],
            ["💯", "hundred points perfect score"],
            ["💢", "anger symbol mad"],
            ["♨️", "hot springs"],
            ["🚷", "no pedestrians"],
            ["🚯", "no littering"],
            ["🚳", "no bicycles"],
            ["🚱", "non potable water"],
            ["🔞", "no one under eighteen adult"],
            ["📵", "no mobile phones"],
            ["🚭", "no smoking"],
            ["❗", "exclamation mark important"],
            ["❕", "white exclamation"],
            ["❓", "question mark help"],
            ["❔", "white question"],
            ["‼️", "double exclamation"],
            ["⁉️", "exclamation question"],
            ["🔅", "dim button brightness low"],
            ["🔆", "bright button brightness high"],
            ["〽️", "part alternation mark"],
            ["⚠️", "warning caution alert"],
            ["🚸", "children crossing"],
            ["🔱", "trident emblem"],
            ["⚜️", "fleur de lis"],
            ["🔰", "japanese symbol beginner"],
            ["♻️", "recycling symbol recycle"],
            ["✅", "check mark button yes done"],
            ["🈯", "reserved japanese"],
            ["💹", "chart yen increasing money"],
            ["❇️", "sparkle star"],
            ["✳️", "eight spoked asterisk"],
            ["❎", "cross mark button no"],
            ["🌐", "globe meridians internet world"],
            ["💠", "diamond shape cute"],
            ["Ⓜ️", "circled m metro"],
            ["🌀", "cyclone swirl"],
            ["💤", "zzz sleep tired"],
            ["🏧", "atm sign money"],
            ["🚾", "water closet restroom bathroom"],
            ["♿", "wheelchair symbol accessible"],
            ["🅿️", "p button parking"],
            ["🛗", "elevator lift"],
            ["🈳", "vacant japanese empty"],
            ["🈂️", "service charge japanese"],
            ["ℹ️", "information info"],
            ["🔤", "input latin letters abc"],
            ["🔡", "input latin lowercase"],
            ["🔠", "input latin uppercase"],
            ["🆖", "ng button no good"],
            ["🆗", "ok button okay"],
            ["🆙", "up button"],
            ["🆒", "cool button"],
            ["🆕", "new button"],
            ["🆓", "free button"],
            ["0️⃣", "zero keycap"],
            ["1️⃣", "one keycap"],
            ["2️⃣", "two keycap"],
            ["3️⃣", "three keycap"],
            ["4️⃣", "four keycap"],
            ["5️⃣", "five keycap"],
            ["6️⃣", "six keycap"],
            ["7️⃣", "seven keycap"],
            ["8️⃣", "eight keycap"],
            ["9️⃣", "nine keycap"],
            ["🔟", "ten keycap"],
            ["🔢", "input numbers 123"],
            ["#️⃣", "hash keycap pound"],
            ["*️⃣", "asterisk keycap star"],
            ["⏏️", "eject button"],
            ["▶️", "play button"],
            ["⏸️", "pause button"],
            ["⏯️", "play pause button"],
            ["⏹️", "stop button"],
            ["⏺️", "record button"],
            ["⏭️", "next track button skip"],
            ["⏮️", "last track button previous"],
            ["⏩", "fast forward"],
            ["⏪", "fast reverse rewind"],
            ["⏫", "fast up"],
            ["⏬", "fast down"],
            ["◀️", "reverse button back"],
            ["🔼", "up button triangle"],
            ["🔽", "down button triangle"],
            ["➡️", "right arrow"],
            ["⬅️", "left arrow"],
            ["⬆️", "up arrow"],
            ["⬇️", "down arrow"],
            ["↗️", "up right arrow"],
            ["↘️", "down right arrow"],
            ["↙️", "down left arrow"],
            ["↖️", "up left arrow"],
            ["↕️", "up down arrow"],
            ["↔️", "left right arrow"],
            ["↩️", "right arrow curving left undo"],
            ["↪️", "left arrow curving right"],
            ["⤴️", "right arrow curving up"],
            ["⤵️", "right arrow curving down"],
            ["🔀", "shuffle tracks random"],
            ["🔁", "repeat button loop"],
            ["🔂", "repeat single one"],
            ["🔄", "counterclockwise arrows refresh reload"],
            ["🔃", "clockwise vertical arrows reload"],
            ["🎵", "musical note music"],
            ["🎶", "musical notes music"],
            ["➕", "plus add math"],
            ["➖", "minus subtract math"],
            ["➗", "divide math"],
            ["✖️", "multiply x math"],
            ["♾️", "infinity forever"],
            ["💲", "heavy dollar sign money"],
            ["💱", "currency exchange money"],
            ["™️", "trade mark tm"],
            ["©️", "copyright"],
            ["®️", "registered"],
            ["👁️‍🗨️", "eye speech bubble witness"],
            ["🔚", "end arrow finish"],
            ["🔙", "back arrow return"],
            ["🔛", "on arrow"],
            ["🔝", "top arrow"],
            ["🔜", "soon arrow coming"],
            ["✔️", "check mark tick yes done"],
            ["☑️", "check box done"],
            ["🔘", "radio button"],
            ["⚪", "white circle"],
            ["⚫", "black circle"],
            ["🔴", "red circle"],
            ["🔵", "blue circle"],
            ["🟤", "brown circle"],
            ["🟠", "orange circle"],
            ["🟡", "yellow circle"],
            ["🟢", "green circle"],
            ["🟣", "purple circle"],
            ["🟥", "red square"],
            ["🟧", "orange square"],
            ["🟨", "yellow square"],
            ["🟩", "green square"],
            ["🟦", "blue square"],
            ["🟪", "purple square"],
            ["🟫", "brown square"],
            ["⬛", "black large square"],
            ["⬜", "white large square"],
            ["◼️", "black medium square"],
            ["◻️", "white medium square"],
            ["◾", "black medium small square"],
            ["◽", "white medium small square"],
            ["▪️", "black small square"],
            ["▫️", "white small square"],
            ["🔶", "large orange diamond"],
            ["🔷", "large blue diamond"],
            ["🔸", "small orange diamond"],
            ["🔹", "small blue diamond"],
            ["🔺", "red triangle pointed up"],
            ["🔻", "red triangle pointed down"],
            ["💠", "diamond with dot"],
            ["🔳", "white square button"],
            ["🔲", "black square button"]
        ]
    },
    {
        id: "flags",
        icon: "🏁",
        label: "Flags",
        items: [
            ["🏁", "chequered flag race finish"],
            ["🚩", "triangular flag"],
            ["🎌", "crossed flags japan"],
            ["🏴", "black flag"],
            ["🏳️", "white flag surrender"],
            ["🏳️‍🌈", "rainbow flag pride lgbtq"],
            ["🏳️‍⚧️", "transgender flag pride"],
            ["🏴‍☠️", "pirate flag"],
            ["🇺🇸", "flag united states america usa"],
            ["🇬🇧", "flag united kingdom britain uk"],
            ["🇨🇦", "flag canada"],
            ["🇦🇺", "flag australia"],
            ["🇳🇿", "flag new zealand"],
            ["🇮🇪", "flag ireland"],
            ["🇫🇷", "flag france french"],
            ["🇩🇪", "flag germany german"],
            ["🇪🇸", "flag spain spanish"],
            ["🇮🇹", "flag italy italian"],
            ["🇵🇹", "flag portugal portuguese"],
            ["🇳🇱", "flag netherlands dutch"],
            ["🇧🇪", "flag belgium"],
            ["🇨🇭", "flag switzerland swiss"],
            ["🇦🇹", "flag austria"],
            ["🇸🇪", "flag sweden swedish"],
            ["🇳🇴", "flag norway norwegian"],
            ["🇩🇰", "flag denmark danish"],
            ["🇫🇮", "flag finland finnish"],
            ["🇵🇱", "flag poland polish"],
            ["🇨🇿", "flag czechia czech"],
            ["🇭🇺", "flag hungary hungarian"],
            ["🇷🇴", "flag romania romanian"],
            ["🇬🇷", "flag greece greek"],
            ["🇹🇷", "flag turkey turkish"],
            ["🇷🇺", "flag russia russian"],
            ["🇺🇦", "flag ukraine ukrainian"],
            ["🇯🇵", "flag japan japanese"],
            ["🇰🇷", "flag south korea korean"],
            ["🇨🇳", "flag china chinese"],
            ["🇹🇼", "flag taiwan"],
            ["🇭🇰", "flag hong kong"],
            ["🇮🇳", "flag india indian"],
            ["🇵🇰", "flag pakistan"],
            ["🇧🇩", "flag bangladesh"],
            ["🇹🇭", "flag thailand thai"],
            ["🇻🇳", "flag vietnam vietnamese"],
            ["🇵🇭", "flag philippines filipino"],
            ["🇮🇩", "flag indonesia indonesian"],
            ["🇲🇾", "flag malaysia malaysian"],
            ["🇸🇬", "flag singapore"],
            ["🇧🇷", "flag brazil brazilian"],
            ["🇦🇷", "flag argentina"],
            ["🇲🇽", "flag mexico mexican"],
            ["🇨🇴", "flag colombia colombian"],
            ["🇨🇱", "flag chile chilean"],
            ["🇵🇪", "flag peru peruvian"],
            ["🇿🇦", "flag south africa"],
            ["🇳🇬", "flag nigeria nigerian"],
            ["🇪🇬", "flag egypt egyptian"],
            ["🇰🇪", "flag kenya kenyan"],
            ["🇮🇱", "flag israel israeli"],
            ["🇸🇦", "flag saudi arabia"],
            ["🇦🇪", "flag united arab emirates uae"],
            ["🇶🇦", "flag qatar"],
            ["🇮🇷", "flag iran iranian"],
            ["🇮🇶", "flag iraq iraqi"]
        ]
    }
];

function loadRecent() {
    try {
        const raw = localStorage.getItem(RECENT_KEY);
        const parsed = raw ? JSON.parse(raw) : [];
        return Array.isArray(parsed) ? parsed.filter(Boolean).slice(0, RECENT_MAX) : [];
    } catch {
        return [];
    }
}

function saveRecent(emoji) {
    if (!emoji) return;
    const next = [emoji, ...loadRecent().filter((item) => item !== emoji)].slice(0, RECENT_MAX);
    try {
        localStorage.setItem(RECENT_KEY, JSON.stringify(next));
    } catch {
        /* ignore quota errors */
    }
}

function flattenSearchIndex() {
    const rows = [];
    for (const category of EMOJI_CATEGORIES) {
        for (const [emoji, names] of category.items) {
            rows.push({ emoji, names: names.toLowerCase(), categoryId: category.id });
        }
    }
    return rows;
}

const SEARCH_INDEX = flattenSearchIndex();

/**
 * Mount a Discord-style emoji picker.
 * @param {{ container: HTMLElement, toggleButton?: HTMLElement|null, onSelect: (emoji: string) => void, onOpen?: () => void, onClose?: () => void, floating?: boolean }} options
 */
export function mountEmojiPicker({ container, toggleButton = null, onSelect, onOpen, onClose, floating = false }) {
    if (!container) return { open: () => {}, close: () => {}, isOpen: () => false, openAt: () => {} };

    let open = false;
    let activeCategory = "smileys";
    let recent = loadRecent();

    container.classList.add("emoji-picker");
    if (floating) container.classList.add("emoji-picker--floating");
    container.innerHTML =
        `<div class="emoji-picker-search-wrap">` +
        `<input type="text" class="emoji-picker-search" placeholder="Search emojis" autocomplete="off" aria-label="Search emojis" />` +
        `</div>` +
        `<div class="emoji-picker-body">` +
        `<div class="emoji-picker-category-label" id="emojiPickerCategoryLabel"></div>` +
        `<div class="emoji-picker-grid" id="emojiPickerGrid" role="grid"></div>` +
        `</div>` +
        `<div class="emoji-picker-tabs" id="emojiPickerTabs" role="tablist"></div>`;

    const searchInput = container.querySelector(".emoji-picker-search");
    const categoryLabel = container.querySelector("#emojiPickerCategoryLabel");
    const grid = container.querySelector("#emojiPickerGrid");
    const tabs = container.querySelector("#emojiPickerTabs");

    function setOpen(next) {
        open = next;
        container.classList.toggle("hidden", !open);
        if (toggleButton) {
            toggleButton.classList.toggle("is-active", open);
            toggleButton.setAttribute("aria-expanded", open ? "true" : "false");
        }
        if (open) {
            onOpen?.();
            searchInput.value = "";
            render();
            searchInput.focus();
        } else {
            onClose?.();
            if (floating) {
                container.style.left = "";
                container.style.top = "";
                container.style.width = "";
            }
        }
    }

    function close() {
        if (open) setOpen(false);
    }

    function openPicker() {
        setOpen(true);
    }

    function toggle() {
        setOpen(!open);
    }

    function renderTabs() {
        const tabItems = [
            { id: "recent", icon: "🕘", label: "Recent" },
            ...EMOJI_CATEGORIES.map((cat) => ({ id: cat.id, icon: cat.icon, label: cat.label }))
        ];
        tabs.innerHTML = tabItems
            .map(
                (tab) =>
                    `<button type="button" class="emoji-picker-tab${tab.id === activeCategory ? " is-active" : ""}"` +
                    ` role="tab" aria-selected="${tab.id === activeCategory ? "true" : "false"}"` +
                    ` data-category="${tab.id}" title="${tab.label}" aria-label="${tab.label}">` +
                    `<span aria-hidden="true">${tab.icon}</span></button>`
            )
            .join("");
    }

    function renderGrid(items, label) {
        categoryLabel.textContent = label;
        if (!items.length) {
            grid.innerHTML = `<div class="emoji-picker-empty">No emojis found</div>`;
            return;
        }
        grid.innerHTML = items
            .map(
                (item) =>
                    `<button type="button" class="emoji-picker-cell" role="gridcell"` +
                    ` data-emoji="${item.emoji}" title="${item.names || item.emoji}" aria-label="${item.names || item.emoji}">` +
                    `${item.emoji}</button>`
            )
            .join("");
    }

    function itemsForCategory(categoryId) {
        if (categoryId === "recent") {
            recent = loadRecent();
            return recent.map((emoji) => ({ emoji, names: "Recent" }));
        }
        const category = EMOJI_CATEGORIES.find((cat) => cat.id === categoryId);
        if (!category) return [];
        return category.items.map(([emoji, names]) => ({ emoji, names }));
    }

    function render() {
        const query = searchInput.value.trim().toLowerCase();
        renderTabs();
        if (query) {
            const results = SEARCH_INDEX.filter((row) => row.names.includes(query) || row.emoji.includes(query))
                .slice(0, 180)
                .map((row) => ({ emoji: row.emoji, names: row.names }));
            renderGrid(results, "Search results");
            return;
        }
        const label =
            activeCategory === "recent"
                ? "Frequently Used"
                : EMOJI_CATEGORIES.find((cat) => cat.id === activeCategory)?.label || "Emojis";
        renderGrid(itemsForCategory(activeCategory), label);
    }

    function openAt(anchorEl) {
        if (!floating || !anchorEl) {
            openPicker();
            return;
        }
        const rect = anchorEl.getBoundingClientRect();
        const width = Math.min(352, window.innerWidth - 16);
        let left = rect.left;
        if (left + width > window.innerWidth - 8) left = window.innerWidth - width - 8;
        if (left < 8) left = 8;
        let top = rect.top - 8;
        container.style.left = `${left}px`;
        container.style.width = `${width}px`;
        container.style.bottom = "auto";
        container.style.top = "auto";
        setOpen(true);
        requestAnimationFrame(() => {
            const pickerHeight = container.offsetHeight || 380;
            top = rect.top - pickerHeight - 8;
            if (top < 8) top = rect.bottom + 8;
            container.style.top = `${top}px`;
        });
    }

    if (toggleButton) {
        toggleButton.addEventListener("click", (e) => {
            e.stopPropagation();
            toggle();
        });
        toggleButton.setAttribute("aria-haspopup", "dialog");
        toggleButton.setAttribute("aria-expanded", "false");
    }

    searchInput.addEventListener("input", render);

    searchInput.addEventListener("keydown", (e) => {
        if (e.key === "Escape") {
            e.preventDefault();
            e.stopPropagation();
            close();
            toggleButton?.focus();
        }
    });

    tabs.addEventListener("click", (e) => {
        const btn = e.target.closest("[data-category]");
        if (!btn) return;
        activeCategory = btn.dataset.category;
        searchInput.value = "";
        render();
    });

    grid.addEventListener("click", (e) => {
        const btn = e.target.closest("[data-emoji]");
        if (!btn) return;
        const emoji = btn.dataset.emoji || "";
        if (!emoji) return;
        saveRecent(emoji);
        onSelect(emoji);
        close();
    });

    container.addEventListener("mousedown", (e) => {
        e.preventDefault();
    });

    document.addEventListener("click", (e) => {
        if (!open) return;
        if (e.target.closest(".emoji-picker")) return;
        if (toggleButton && e.target.closest(".emoji-toggle")) return;
        if (e.target.closest("[data-msg-action='open-reactions']")) return;
        close();
    });

    return { open: openPicker, close, isOpen: () => open, toggle, openAt };
}
