// Shared prompt/question banks (used by studio + prompt notebook).

export const WEEKLY_PROMPTS_52 = [
  "Respond as your character:\n\n“You're dead... I killed you... h-how are you...?!“",
  "Respond as your character:\n\n“<em>You should</em> thank me.” she spat. “I did this all for you.”",
  "Respond as your character:\n\nHow would your character say “I hate you” without saying it?",
  "Respond as your character:\n\nThe Angel of Death beckons. How does your character respond?",
  "Respond as your character:\n\n“Okay, [insert character name], I need you to cause a small distraction.”",
  "Respond as your character:\n\n“You were never supposed to survive that.”",
  "Respond as your character:\n\nSomeone whispers, “We can still fix this.”",
  "Respond as your character:\n\nYour character is accused of a crime they didn’t commit. How do they respond?",
  "Respond as your character:\n\n“I trusted you.” How does your character respond?",
  "Respond as your character:\n\nA child asks, “Are you a hero?” What is the answer?",
  "Respond as your character:\n\nYour character must lie to save a life. What do they say?",
  "Respond as your character:\n\n“If you walk away now, you can never come back.” What does your character do?",
  "Respond as your character:\n\nSomeone offers forgiveness your character doesn’t deserve. What happens?",
  "Respond as your character:\n\nYour character meets someone they betrayed. What happens?",
  "Respond as your character:\n\n“Say it again.” What does your character do?",
  "Respond as your character:\n\nYour character is told, “You are the reason this world is breaking.” What is their response?",
  "Respond as your character:\n\nA god speaks your character’s true name. What happens?",
  "Respond as your character:\n\n“I could fix you.” What does your character say?",
  "Respond as your character:\n\nYour character is offered revenge on their greatest enemy. What do they do?",
  "Respond as your character:\n\n“You don’t get to die yet.” What happens next?",
  "Respond as your character:\n\nYour character wakes up in a place where they are worshipped. What do they do first?",
  "Respond as your character:\n\nSomeone says, “You’ve changed.” What is the response?",
  "Respond as your character:\n\nYour character must choose between two loved ones. What do they do?",
  "Respond as your character:\n\n“This is your fault.” What does your character say?",
  "Respond as your character:\n\nA villain offers your character a place beside them. What is the response?",
  "Respond as your character:\n\nYour character learns the truth about their origin. What do they do?",
  "Respond as your character:\n\n“Kill me, and you’ll understand everything.” What happens?",
  "Respond as your character:\n\nSomeone begs, “Don’t become like me.” What is your character’s response?",
  "Respond as your character:\n\nYour character must choose: save one person or erase a war. What do they choose?",
  "Respond as your character:\n\n“You always were the weak one.” What does your character say?",
  "Respond as your character:\n\nA friend says, “I would’ve followed you anywhere.” What does your character realize?",
  "Respond as your character:\n\nYour character is asked what they fear most. What do they say?",
  "Respond as your character:\n\n“We both know how this ends.” What happens?",
  "Respond as your character:\n\nYour character speaks at the funeral of their enemy. What do they say?",
  "Respond as your character:\n\nSomeone offers your character peace. What do they do?",
  "Respond as your character:\n\n“Prove you’re human.” What is the response?",
  "Respond as your character:\n\nYour character is the last person who remembers the truth. What do they do?",
  "Respond as your character:\n\n“You were never the hero.” What is the response?",
  "Respond as your character:\n\nA child copies your character’s worst habit. What happens?",
  "Respond as your character:\n\nYour character is asked to smile for a portrait that will define history. What do they do?",
  "Respond as your character:\n\n“Tell me a secret.” What secret is given?",
  "Respond as your character:\n\nYour character is offered redemption if they forget everything. What do they refuse?",
  "Respond as your character:\n\n“You’re not welcome here.” What does your character do?",
  "Respond as your character:\n\nSomeone says your character is the prophecy. What is the response?",
  "Respond as your character:\n\nYour character must kill someone they have already forgiven. What happens?",
  "Respond as your character:\n\n“You’re too late.” What does your character say?",
  "Respond as your character:\n\nA god asks your character for advice. What do they say?",
  "Respond as your character:\n\nYour character is offered immortality. What do they do?",
  "Respond as your character:\n\n“Do you regret it?” What is the answer?",
  "Respond as your character:\n\nSomeone asks, “What are you?” What is the answer?",
  "Respond as your character:\n\nYour character stands before who they used to be. What happens?",
  "Respond as your character:\n\nWrite the sentence that defines your character completely."
];

export const DAILY_CHARACTER_Q = [
  "What does your character want more than anything, and why?",
  "What does your character fear losing most?",
  "What event permanently shaped your character’s personality?",
  "What lie does your character believe about themselves?",
  "What truth about themselves do they refuse to accept?",
  "What is your character’s greatest strength?",
  "What is your character’s greatest flaw?",
  "What would your character die for without hesitation?",
  "What would your character never sacrifice, no matter what?",
  "What does your character regret most?",
  "Who does your character trust most, and why?",
  "Who does your character trust least, and why?",
  "What does your character want people to think of them?",
  "What is your character actually like when no one is watching?",
  "What is your character’s biggest secret?",
  "What would destroy your character emotionally if revealed?",
  "What is your character’s moral code?",
  "What line will your character never cross?",
  "What line has your character already crossed?",
  "What does your character believe about power?",
  "What does your character believe about love?",
  "What does your character believe about death?",
  "What does your character believe about themselves?",
  "What does your character believe about others?",
  "What does your character value more than life itself?",
  "What does your character value more than loyalty?",
  "What does your character do when they are angry?",
  "What does your character do when they are afraid?",
  "What does your character do when they are heartbroken?",
  "What does your character do when they are in love?",
  "What is your character’s biggest insecurity?",
  "What makes your character feel powerful?",
  "What makes your character feel powerless?",
  "What does your character want to forget?",
  "What does your character wish they remembered?",
  "What is your character’s worst memory?",
  "What is your character’s happiest memory?",
  "What does your character hide from the world?",
  "What does your character show the world instead?",
  "What is your character’s deepest desire?",
  "What is your character’s greatest fear?",
  "What motivates your character to keep going?",
  "What almost made your character give up?",
  "What does your character consider “home”?",
  "Where does your character feel most out of place?",
  "Who changed your character’s life forever?",
  "Who did your character change forever?",
  "What does your character owe someone?",
  "What does someone owe your character?",
  "What would your character do for revenge?",
  "What would stop your character from seeking revenge?",
  "What is your character’s relationship with authority?",
  "What is your character’s relationship with chaos?",
  "What does your character think about rules?",
  "What rules does your character follow anyway?",
  "What rules does your character break constantly?",
  "What does your character lie about most often?",
  "What truth does your character say too often?",
  "What does your character want to be remembered for?",
  "What will your character likely be remembered for?",
  "What is your character’s greatest accomplishment?",
  "What is your character’s greatest failure?",
  "What does your character avoid thinking about?",
  "What thought haunts your character daily?",
  "What does your character do when no one understands them?",
  "What does your character do when they feel understood?",
  "What does your character hide even from themselves?",
  "What would make your character betray someone they love?",
  "What would make your character stay loyal no matter what?",
  "What is your character’s biggest contradiction?",
  "What does your character pretend not to care about?",
  "What does your character secretly care deeply about?",
  "What makes your character feel alive?",
  "What makes your character feel empty?",
  "What does your character run from?",
  "What does your character run toward?",
  "What is your character’s greatest skill?",
  "What is your character’s least useful skill?",
  "What does your character wish they could change about themselves?",
  "What would your character never change about themselves?",
  "What does your character think of forgiveness?",
  "What does your character think of redemption?",
  "What does your character think of justice?",
  "What does your character think of revenge?",
  "What does your character think of love at first sight?",
  "What does your character think of fate?",
  "What does your character think of free will?",
  "What is your character’s biggest misunderstanding about the world?",
  "What is your character right about that others ignore?",
  "What is your character wrong about but refuses to admit?",
  "What does your character fear becoming?",
  "What does your character already resemble?",
  "What does your character do when they are alone too long?",
  "What does your character do when they are surrounded by people?",
  "What does your character do under pressure?",
  "What breaks your character emotionally?",
  "What heals your character emotionally?",
  "What does your character think is their purpose?",
  "What is their actual purpose in the story?",
  "What would your character change about the world first?",
  "What is your character’s origin story?",
  "What was your character like as a child?",
  "What changed them from who they were?",
  "What lesson did they learn too late?",
  "What lesson did they learn too early?",
  "What shaped their worldview most?",
  "What relationship defined their childhood?",
  "What relationship destroyed their childhood?",
  "What did they lose first in life?",
  "What did they gain too early?",
  "What promise did they make and break?",
  "What promise did they keep at all costs?",
  "What mistake do they repeat?",
  "What moment do they replay in their mind?",
  "What decision changed everything?",
  "What decision do they still avoid thinking about?",
  "What path did they abandon?",
  "What path did they never choose but still follow?",
  "What was their first failure?",
  "What was their first victory?",
  "Who taught your character the most important lesson?",
  "Who betrayed your character first?",
  "Who did your character betray first?",
  "Who saved your character?",
  "Who did your character fail to save?",
  "What shaped their beliefs about love?",
  "What shaped their beliefs about violence?",
  "What shaped their beliefs about authority?",
  "What shaped their beliefs about trust?",
  "What shaped their beliefs about survival?",
  "What is the most traumatic event in their life?",
  "What is the most defining peaceful moment?",
  "What do they miss from their past?",
  "What do they refuse to return to?",
  "What did they used to believe that they no longer do?",
  "What belief replaced it?",
  "What did they once want but no longer do?",
  "What did they never expect to want?",
  "What is their earliest memory?",
  "What memory is distorted in their mind?",
  "What truth did they discover too young?",
  "What truth did they avoid for years?",
  "What story were they told growing up?",
  "What story did they later learn was false?",
  "What shaped their sense of morality?",
  "What shattered their sense of morality?",
  "What do they blame themselves for?",
  "What do they wrongly blame others for?",
  "What shaped their identity most?",
  "What identity did they reject?",
  "How does your character speak under stress?",
  "How does your character speak when lying?",
  "How does your character speak when telling the truth?",
  "What words does your character never say?",
  "What phrase defines your character?",
  "What tone is your character most comfortable in?",
  "How does your character handle silence?",
  "What does your character say too much?",
  "What do they never say enough?",
  "What do they say only once?",
  "How does your character react to insult?",
  "How does your character react to praise?",
  "How does your character react to betrayal?",
  "How does your character react to affection?",
  "How does your character react to authority?",
  "How does your character react to being ignored?",
  "How does your character react to being needed?",
  "How does your character react to failure?",
  "How does your character react to success?",
  "How does your character react to loss?",
  "What does your character’s voice reveal?",
  "What does your character hide in their tone?",
  "What is your character’s communication style?",
  "How does your character lie convincingly?",
  "How does your character fail to lie?",
  "What is your character’s default emotional state?",
  "What emotion do they suppress most?",
  "What emotion do they express too easily?",
  "What triggers your character?",
  "What calms your character?",
  "What makes your character act impulsively?",
  "What makes your character hesitate?",
  "What makes your character decisive?",
  "What makes your character freeze?",
  "What does your character notice that others don’t?",
  "What does your character miss that others see?",
  "How does your character handle confrontation?",
  "How does your character avoid confrontation?",
  "What is your character’s default reaction to danger?",
  "What is your character’s default reaction to safety?",
  "How does your character express affection?",
  "How does your character reject affection?",
  "What does your character assume about strangers?",
  "What do strangers assume about your character?",
  "How does your character change when angry?",
  "How does your character change when sad?",
  "How does your character change when happy?",
  "How does your character change when in love?",
  "What does your character sound like at their breaking point?",
  "What does your character sound like when healed?",
  "What does your character carry physically that matters emotionally?",
  "What object does your character refuse to lose?",
  "What object does your character hide?",
  "What object reminds them of their past?",
  "What object represents their future?",
  "What weapon (literal or metaphorical) defines them?",
  "What tool does your character rely on most?",
  "What resource do they always run out of?",
  "What skill do they overestimate?",
  "What skill do they underestimate?",
  "What does your character depend on too much?",
  "What do they refuse to depend on?",
  "What is your character’s survival strategy?",
  "What is your character’s downfall strategy?",
  "What does your character protect at all costs?",
  "What does your character neglect?",
  "What habit defines your character?",
  "What habit destroys them slowly?",
  "What pattern repeats in their life?",
  "What pattern do they try to break?",
  "What is your character’s coping mechanism?",
  "What coping mechanism fails them?",
  "What do they do when overwhelmed?",
  "What do they do when calm?",
  "What do they do when bored?",
  "What do they do when inspired?",
  "What do they do when cornered?",
  "What do they do when given freedom?",
  "What do they do when no one is watching?",
  "What do they do when everyone is watching?",
  "What does your character collect or hoard?",
  "What do they refuse to keep?",
  "What do they repair instead of replacing?",
  "What do they abandon too quickly?",
  "What do they take for granted?",
  "What do they value too highly?",
  "What is your character’s routine?",
  "What breaks their routine?",
  "What structure do they rely on?",
  "What structure do they reject?",
  "What does your character build?",
  "What does your character destroy?",
  "What do they create unintentionally?",
  "What do they ruin unintentionally?",
  "What is your character’s environment like?",
  "How does environment shape them?",
  "What makes them feel unsafe?",
  "What makes them feel secure?",
  "What is their survival weakness?",
  "What is their survival strength?",
  "Who would your character kill without hesitation?",
  "Who would your character never harm?",
  "Who does your character admire?",
  "Who does your character despise?",
  "Who does your character envy?",
  "Who does your character pity?",
  "Who does your character fear?",
  "Who does your character respect?",
  "Who does your character underestimate?",
  "Who does your character overestimate?",
  "Who changed your character’s path?",
  "Who could still change their path?",
  "Who is your character’s rival?",
  "Who is your character’s ally?",
  "Who is your character’s enemy?",
  "Who is your character’s weakness in human form?",
  "Who brings out the best in your character?",
  "Who brings out the worst?",
  "Who does your character protect silently?",
  "Who does your character resent silently?",
  "Who does your character miss?",
  "Who does your character wish they never met?",
  "Who does your character owe everything to?",
  "Who owes everything to your character?",
  "Who betrayed your character completely?",
  "Who did your character betray completely?",
  "Who does your character still love?",
  "Who do they wish they didn’t love?",
  "Who knows your character best?",
  "Who thinks they know your character best?",
  "Who is your character closest to?",
  "Who is emotionally closest but physically distant?",
  "Who does your character protect from themselves?",
  "Who protects your character?",
  "Who is your character trying to become?",
  "Who is your character trying not to become?",
  "Who reflects your character’s flaws?",
  "Who reflects your character’s strengths?",
  "Who would your character follow blindly?",
  "Who would your character refuse to follow?",
  "Who does your character forgive too easily?",
  "Who does your character never forgive?",
  "Who challenges your character?",
  "Who enables your character?",
  "Who misunderstands your character most?",
  "Who understands your character too well?",
  "Who would your character sacrifice for?",
  "Who would never be sacrificed?",
  "Who defines your character’s loyalty?",
  "Who breaks your character’s loyalty?",
  "What is your character’s greatest dream?",
  "What is their worst nightmare?",
  "What is their long-term goal?",
  "What is their short-term goal?",
  "What goal are they lying about?",
  "What goal are they ashamed of?",
  "What goal do they not fully understand?",
  "What goal did they abandon?",
  "What goal refuses to die?",
  "What goal changed over time?",
  "What does your character think they need?",
  "What do they actually need?",
  "What do they think will make them happy?",
  "What actually makes them happy?",
  "What do they chase endlessly?",
  "What do they avoid endlessly?",
  "What would they do with unlimited power?",
  "What would they do with no power at all?",
  "What would they do with unlimited time?",
  "What would they do with no time left?",
  "What would they build if nothing could stop them?",
  "What would they destroy if nothing could stop them?",
  "What future do they imagine?",
  "What future are they actually heading toward?",
  "What do they sacrifice first?",
  "What do they sacrifice last?",
  "What opportunity did they miss?",
  "What opportunity changed everything?",
  "What choice defines them?",
  "What choice haunts them?",
  "What do they want to prove?",
  "Who do they want to prove it to?",
  "What do they want to be right about?",
  "What do they fear being right about?",
  "What would make them quit everything?",
  "What would make them push forward anyway?",
  "What is their breaking point?",
  "What is their recovery point?",
  "What do they think is impossible?",
  "What turns out to be possible?",
  "What do they underestimate?",
  "What do they overestimate?",
  "What do they ignore?",
  "What do they obsess over?",
  "What do they misunderstand about themselves?",
  "What do they finally understand about themselves?",
  "What changes their worldview?",
  "What reinforces their worldview?",
  "What truth would ruin them?",
  "What truth would save them?",
  "What do they want others to believe about them?",
  "What is actually true about them?",
  "What would they never admit out loud?",
  "What do they confess under pressure?",
  "What do they want to become?",
  "What are they becoming?",
  "What is their end goal in life?",
  "What is their unspoken goal?",
  "What do they think defines success?",
  "What actually defines success for them?",
  "What do they want their final moment to mean?",
  "What do they fear their final moment will be?",
  "What will their legacy likely be?",
  "What legacy do they want?",
  "What question defines your character completely?"
];

export const DAILY_WORLDBUILD_Q = [
  "What is the origin myth of this world?",
  "What do people believe created the world?",
  "What is actually responsible for the world’s creation?",
  "How old is the world?",
  "What major eras divide its history?",
  "What is the most important historical turning point?",
  "What is the dominant geography of the world?",
  "What climates exist and where?",
  "What natural disaster most shaped civilization?",
  "What is the rarest natural phenomenon?",
  "What resources are most valuable?",
  "What resource is abundant but overlooked?",
  "What resource caused ancient wars?",
  "What is the largest unexplored region?",
  "What is the smallest inhabited region?",
  "What continents or landmasses exist?",
  "What lies beyond the known map?",
  "What natural barriers divide civilizations?",
  "What is the most dangerous environment?",
  "What is the safest environment?",
  "What ecosystems are unique to this world?",
  "What species dominate the landscape?",
  "What species are nearly extinct?",
  "What species are newly evolved or discovered?",
  "What role does magic (if any) play in nature?",
  "How does technology interact with nature?",
  "What natural laws differ from Earth’s?",
  "What is considered a “miracle” in this world?",
  "What is considered a “curse” in nature?",
  "What celestial bodies influence the world?",
  "How many moons or suns exist?",
  "How do tides or seasons differ?",
  "What unusual weather patterns exist?",
  "What is the longest recorded storm?",
  "What is the shortest season?",
  "What natural sound defines the world?",
  "What natural light phenomenon is common?",
  "What is the most sacred natural place?",
  "What is the most feared natural place?",
  "What is the oldest living organism?",
  "What is the largest living structure?",
  "What is the most widespread biome?",
  "What biome is disappearing?",
  "What biome is expanding?",
  "How do natural cycles affect society?",
  "What geological activity is constant?",
  "What underground systems exist?",
  "What oceans/seas are most important?",
  "What islands are culturally significant?",
  "What natural resource is tied to religion?",
  "What is the dominant form of government?",
  "What form of government is banned?",
  "How many major nations exist?",
  "What is the largest empire in history?",
  "What is the smallest independent state?",
  "How are leaders chosen?",
  "What makes a leader illegitimate?",
  "What is the most common social structure?",
  "What social class is most powerful?",
  "What social class is most oppressed?",
  "How is justice enforced?",
  "What is the punishment for theft?",
  "What is the punishment for treason?",
  "What rights are universally guaranteed?",
  "What rights are restricted?",
  "How is education handled?",
  "Who has access to knowledge?",
  "What is considered forbidden knowledge?",
  "What is the most common occupation?",
  "What occupation is most dangerous?",
  "What is the most respected profession?",
  "What is the most hated profession?",
  "How do cities typically form?",
  "What is the largest city?",
  "What is the most isolated settlement?",
  "How do people travel between regions?",
  "What is the fastest transportation method?",
  "What is the slowest but most reliable travel method?",
  "What languages exist?",
  "Is there a universal language?",
  "How do cultures blend or clash?",
  "What cultural taboo exists everywhere?",
  "What is a common greeting?",
  "What is a common insult?",
  "What are naming conventions like?",
  "How do families form?",
  "What defines adulthood?",
  "What rituals mark birth or death?",
  "What festivals are widely celebrated?",
  "What festival is the most controversial?",
  "How is time measured socially?",
  "What calendars are used?",
  "How is money structured?",
  "What is the most valuable currency?",
  "Is barter still common?",
  "What items function as currency in some regions?",
  "How is property ownership defined?",
  "What is considered public vs private space?",
  "What is the role of religion in governance?",
  "Are there theocracies?",
  "What religions dominate?",
  "What religions are persecuted?",
  "What are common superstitions?",
  "What myths influence daily life?",
  "What historical figures are mythologized?",
  "Who is erased from history?",
  "What monuments exist?",
  "What monuments were destroyed?",
  "What art forms are most valued?",
  "What art is considered illegal?",
  "What is the most popular entertainment?",
  "What sport dominates culture?",
  "What sport is forbidden?",
  "What foods are culturally central?",
  "What foods are taboo?",
  "How do people typically dress?",
  "What clothing symbolizes status?",
  "What materials are used in daily life?",
  "How do cities handle waste?",
  "What is considered luxury?",
  "Does magic exist in this world?",
  "If so, what is its source?",
  "Who can use magic?",
  "What limits magic use?",
  "What are the consequences of magic misuse?",
  "What is the rarest magical ability?",
  "What is the most common magical ability?",
  "Is magic studied scientifically?",
  "Is magic regulated by law?",
  "Are magical beings separate from humans?",
  "What is the most powerful magical artifact?",
  "What is the most dangerous artifact?",
  "How is technology powered?",
  "What is the most advanced technology?",
  "What is the most primitive surviving tech?",
  "Are magic and technology combined?",
  "What invention changed society most?",
  "What invention is feared?",
  "What invention is lost?",
  "How is communication handled?",
  "How fast is communication across distance?",
  "What forms of transport exist?",
  "Are there flying vehicles?",
  "Are there underwater civilizations?",
  "What energy sources exist?",
  "What energy source is forbidden?",
  "How is medicine practiced?",
  "What diseases are common?",
  "What diseases are incurable?",
  "Is immortality possible?",
  "What are limits on human enhancement?",
  "Are artificial beings created?",
  "Do AI or constructs exist?",
  "What is consciousness in this world?",
  "Can minds be copied or transferred?",
  "What is the strongest known material?",
  "What is the rarest material?",
  "How are weapons developed?",
  "What is the most feared weapon?",
  "What is the most honorable weapon?",
  "How is warfare conducted?",
  "Are there standing armies?",
  "Are there mercenaries?",
  "Are wars common or rare?",
  "What ends a war?",
  "What is considered dishonorable warfare?",
  "What defenses protect cities?",
  "Are there magical defenses?",
  "What is espionage like?",
  "How is information stolen or protected?",
  "What are secret organizations?",
  "Who controls knowledge?",
  "Are there underground networks?",
  "What is the black market like?",
  "What is illegal to trade?",
  "How is crime organized?",
  "What is the most common crime?",
  "What is the most severe punishment?",
  "Are prisons common?",
  "Are there rehabilitation systems?",
  "What is surveillance like?",
  "Who is watched most closely?",
  "How is privacy protected?",
  "What is considered a breach of privacy?",
  "What is propaganda like?",
  "Who controls media?",
  "Is censorship common?",
  "What information is restricted?",
  "How do revolutions form?",
  "What typically sparks rebellion?",
  "What prevents rebellion?",
  "What is diplomacy like?",
  "How are treaties enforced?",
  "What alliances exist?",
  "What betrayals shaped history?",
  "What secret pacts exist?",
  "What is the balance of power?",
  "Who are the superpowers?",
  "What is the weakest state?",
  "What hidden force influences everything?",
  "Who is the most famous historical figure?",
  "Who is the most infamous figure?",
  "Who is forgotten but important?",
  "What hero is actually a villain?",
  "What villain is misunderstood?",
  "What ordinary person changed history?",
  "What is a common personal dream?",
  "What is a common fear?",
  "What motivates most people?",
  "What breaks a person’s beliefs?",
  "What is considered a “good life”?",
  "What is considered failure?",
  "How do friendships form?",
  "How do rivalries begin?",
  "How are romances expressed?",
  "What is a forbidden relationship?",
  "How are marriages arranged or chosen?",
  "What is divorce like?",
  "What role do children play in society?",
  "How are elders treated?",
  "What is inheritance like?",
  "What is a coming-of-age journey?",
  "What is a common tragedy?",
  "What is a common triumph?",
  "What story is told to every child?",
  "What story is banned?",
  "What myths are proven true?",
  "What truths are dismissed as myths?",
  "What is the greatest unsolved mystery?",
  "What is the most famous prophecy?",
  "Has any prophecy come true?",
  "What is a daily routine like?",
  "What does a normal day look like in a city?",
  "What does a normal day look like in a rural area?",
  "What does a soldier’s life look like?",
  "What does a scholar’s life look like?",
  "What does a criminal’s life look like?",
  "What does a ruler’s life look like?",
  "What is the most emotional ritual?",
  "What is the most joyful celebration?",
  "What is the most solemn tradition?",
  "How do people grieve?",
  "What is considered honorable death?",
  "What is considered shameful death?",
  "What happens after death (belief)?",
  "What actually happens after death (truth)?",
  "How do ghosts or spirits interact with the world?",
  "Are dreams meaningful or magical?",
  "What is the most common dream?",
  "What is the most feared nightmare?",
  "What symbols carry deep meaning?",
  "What colors have cultural significance?",
  "What sounds are culturally symbolic?",
  "What gestures are universal?",
  "What gesture is offensive everywhere?",
  "What objects are considered lucky?",
  "What objects are considered cursed?",
  "What is the most traded item emotionally (not economically)?",
  "What is the most sentimental tradition?",
  "What is the hardest thing to lose?",
  "What is the easiest thing to replace?",
  "What defines identity in this world?",
  "How do people change identity?",
  "What secrets does everyone keep?",
  "What secret societies influence daily life?",
  "What is the biggest conspiracy theory?",
  "What conspiracy is actually true?",
  "What is the role of fate vs free will?",
  "Do people believe they control their destiny?",
  "What event reshaped personal identity globally?",
  "What is the most inspiring story?",
  "What is the most cautionary tale?",
  "What is the most misunderstood tradition?",
  "What is the most universal experience?",
  "What divides people the most?",
  "What unites everyone?",
  "What is the most controversial law?",
  "What law is universally accepted?",
  "What is justice according to the average person?",
  "What is justice according to the state?",
  "What is justice according to rebels?",
  "What is considered heroic sacrifice?",
  "What is considered pointless sacrifice?",
  "What is the cost of peace?",
  "What is the cost of war?",
  "What is the most common personal goal?",
  "What is the rarest ambition?",
  "What do people fear losing most?",
  "What do people strive to gain most?",
  "What is the role of art in rebellion?",
  "What is the role of art in propaganda?",
  "What is forbidden creativity?",
  "What is celebrated creativity?",
  "What is the most powerful story ever told?",
  "Who controls storytelling?",
  "Who resists dominant narratives?",
  "What truth would shatter society?",
  "What lie holds society together?",
  "What is the ultimate moral dilemma in this world?",
  "What defines humanity here?",
  "What separates humans from other beings?",
  "What makes someone “other”?",
  "How are outsiders treated?",
  "How are insiders defined?",
  "What is redemption in this world?",
  "What is irredeemable?",
  "What is the most transformative journey?",
  "What is the most static aspect of society?",
  "What changes slowly over centuries?",
  "What changes overnight?",
  "What is the most powerful institution?",
  "What is the most fragile institution?",
  "What is the role of faith?",
  "What is the role of doubt?",
  "What is the most sacred promise?",
  "What promise is never kept?",
  "What is the final question of this world’s philosophy?",
  "What answer do most people accept?",
  "What question are people afraid to ask?",
  "What knowledge is humanity not ready for?",
  "What knowledge changes everything?",
  "What is the cost of truth?",
  "What is the comfort of ignorance?",
  "What is the most defining moment in an individual life?",
  "What is the most defining moment in world history?",
  "What is the smallest act that changes everything?",
  "What is the largest act that changes nothing?",
  "What is the meaning of power?",
  "Who deserves power?",
  "Who has power but should not?",
  "What is the final fate of empires?",
  "What replaces fallen empires?",
  "What remains unchanged forever?",
  "What is the edge of the known world?",
  "What lies beyond it?",
  "Who dares to explore beyond?",
  "What is lost when exploring?",
  "What is gained?",
  "What is the ultimate mystery of existence here?",
  "What is the simplest truth everyone ignores?",
  "What is the most complex lie everyone believes?",
  "What is the role of memory in society?",
  "Who controls collective memory?",
  "What is forgotten intentionally?",
  "What cannot be forgotten?",
  "What defines legacy?",
  "Who gets remembered?",
  "Who gets erased?",
  "What is the final lesson of this world?",
  "What question defines its future?",
  "What is the most hopeful possibility?",
  "What is the darkest possible future?",
  "What is the most likely future?",
  "What choice will determine everything?",
  "What is the price of survival?",
  "What is the price of progress?",
  "What is the price of tradition?",
  "What is the final contradiction of this world?",
  "What is the most beautiful thing in it?",
  "What is the most horrifying thing in it?",
  "What is the thing everyone agrees is true?",
  "What is the thing everyone secretly doubts?",
  "What is the question no one answers?",
  "What is the question that must be answered next?",
  "What will you build from all of this?"
];
