export const els = {
    signupCard: document.getElementById("signup-card"),
    confirmEmailCard: document.getElementById("confirm-email-card"),
    confirmEmailAddressEl: document.getElementById("confirm-email-address"),
    resendConfirmBtn: document.getElementById("resend-confirm-btn"),
    confirmSuccessEl: document.getElementById("confirm-success-msg"),
    confirmErrorEl: document.getElementById("confirm-error-msg"),
    onboardingCard: document.getElementById("onboarding-card"),
    usernameStep: document.getElementById("username-step"),
    appearanceStep: document.getElementById("appearance-step"),
    pfpStep: document.getElementById("pfp-step"),
    usernameStepDot: document.getElementById("username-step-dot"),
    appearanceStepDot: document.getElementById("appearance-step-dot"),
    pfpStepDot: document.getElementById("pfp-step-dot"),
    finalUsernameInput: document.getElementById("final-username"),
    usernameNextBtn: document.getElementById("username-next-btn"),
    appearanceBackBtn: document.getElementById("appearance-back-btn"),
    appearanceNextBtn: document.getElementById("appearance-next-btn"),
    pfpBackBtn: document.getElementById("pfp-back-btn"),
    finishOnboardingBtn: document.getElementById("finish-onboarding-btn"),
    profilePictureInput: document.getElementById("profile-picture-input"),
    pfpPreview: document.getElementById("pfp-preview"),
    pfpPreviewInitial: document.getElementById("pfp-preview-initial"),
    themeChoiceGrid: document.getElementById("theme-choice-grid"),
    fontChoiceGrid: document.getElementById("font-choice-grid"),
    errorEl: document.getElementById("error-msg"),
    onboardingErrorEl: document.getElementById("onboarding-error-msg"),
    signupBtn: document.getElementById("signup-btn"),
    googleBtn: document.getElementById("google-btn"),
    discordBtn: document.getElementById("discord-btn"),
};

els.oauthButtons = [els.googleBtn, els.discordBtn];
