# Generates js/history-sections.js — one field per questionnaire bullet
import json
from pathlib import Path

def qlist(section_id, questions):
    return [[f"{section_id}_{i}", text] for i, text in enumerate(questions)]

GLYPHS = {
    "origins": "✧", "eras": "⌛", "ancient": "◇", "empires": "⚑", "wars": "⚔",
    "revolutions": "✦", "religion": "☽", "magicHist": "✶", "technology": "⚙",
    "exploration": "🧭", "figures": "✒", "mysteries": "?", "trauma": "◎",
    "dailyLife": "⌂", "economy": "⚖", "culture": "❧", "knowledge": "📜",
    "environment": "△", "hidden": "⊞", "legacy": "→", "meta": "∞",
}

SECTIONS_RAW = [
    ("origins", "Origins of Civilization", [
        "Where did the first civilizations begin?",
        "Why did they begin there?",
        "What resources allowed survival?",
        "What environmental pressures shaped early societies?",
        "Who were the earliest known peoples?",
        "Were they hunter-gatherers?",
        "Nomads?",
        "Agriculturalists?",
        "Seafarers?",
        "Subterranean dwellers?",
        "Something stranger?",
        "What myths exist about the beginning of civilization?",
        "Are those myths true?",
        "What existed before recorded history?",
        "What ancient ruins predate known civilization?",
        "Was there a precursor civilization?",
        "Did civilization emerge naturally or through outside influence?",
        "Did gods influence early history?",
        "Aliens?",
        "Magic?",
        "Ancient beings?",
        "What inventions changed society first?",
        "Agriculture?",
        "Fire?",
        "Writing?",
        "Magic?",
        "Metallurgy?",
        "Domestication?",
        "What resources became valuable earliest?",
        "What social structures formed first?",
        "Who held power originally?",
        "Priests?",
        "Warriors?",
        "Elders?",
        "Scholars?",
        "What early conflicts shaped civilization?",
        "What ancient fears still echo culturally?",
    ]),
    ("eras", "Historical Eras & Timeline", [
        "What major historical eras exist?",
        "What defines the transition between eras?",
        "Conquest?",
        "Collapse?",
        "Religion?",
        "Technology?",
        "Climate?",
        "Magic?",
        "Who decides how eras are remembered?",
        "Are historical eras universally agreed upon?",
        "What cultures divide history differently?",
        "What era is romanticized?",
        "What era is feared?",
        "What era is poorly understood?",
        "What calendar systems exist?",
        "What event marks Year One?",
        "Are years counted from a divine event?",
        "A war?",
        "A coronation?",
        "A cataclysm?",
        "The founding of a civilization?",
        "Do all cultures use the same calendar?",
        "What events disrupted timekeeping?",
        "Were years lost?",
        "Erased?",
        "Fabricated?",
        "Rewritten?",
    ]),
    ("ancient", "Ancient Civilizations", [
        "What was the first major empire or civilization?",
        "How did it rise?",
        "What advantages did it possess?",
        "Geography?",
        "Magic?",
        "Military?",
        "Religion?",
        "Technology?",
        "What cultural achievements defined it?",
        "What beliefs united it?",
        "What enemies threatened it?",
        "What was daily life like?",
        "What architecture did they build?",
        "What language did they speak?",
        "What religion dominated?",
        "What social classes existed?",
        "How did they treat outsiders?",
        "What made them unique historically?",
        "Why did they fall?",
        "War?",
        "Corruption?",
        "Ecological collapse?",
        "Civil war?",
        "Disease?",
        "Divine punishment?",
        "Magical catastrophe?",
        "Did they disappear entirely?",
        "Were survivors absorbed into later cultures?",
        "What ruins remain?",
        "What myths distort the truth of their fall?",
    ]),
    ("empires", "Empires & Expansion", [
        "What empires rose to dominance?",
        "How did they expand?",
        "Conquest?",
        "Trade?",
        "Religion?",
        "Colonization?",
        "Diplomacy?",
        "Marriage?",
        "What justified their expansion?",
        "Civilizing mission?",
        "Divine right?",
        "Survival?",
        "Greed?",
        "Destiny?",
        "What regions resisted them most?",
        "How did empires govern distant territories?",
        "Military occupation?",
        "Local rulers?",
        "Governors?",
        "Tribute systems?",
        "Fear?",
        "Religion?",
        "Propaganda?",
        "What infrastructure unified the empire?",
        "Roads?",
        "Magic portals?",
        "Fleets?",
        "Communication systems?",
        "How were conquered peoples treated?",
        "What weakened the empire?",
        "Overexpansion?",
        "Corruption?",
        "Succession crises?",
        "Economic instability?",
        "Rebellion?",
        "Climate change?",
        "Invasion?",
        "What event symbolized its fall?",
        "Did anyone try to restore it?",
        "What legacy remained?",
    ]),
    ("wars", "Wars & Conflict", [
        "What caused major wars?",
        "Religion?",
        "Territory?",
        "Resources?",
        "Succession?",
        "Revenge?",
        "Ideology?",
        "Fear?",
        "Prophecy?",
        "Magic?",
        "What conflicts lasted generations?",
        "What wars reshaped the world map?",
        "What weapons dominated each era?",
        "What strategies changed warfare forever?",
        "What military leaders became legends?",
        "What battles are studied endlessly?",
        "What military disasters are infamous?",
        "How did civilians suffer?",
        "What atrocities occurred?",
        "What war crimes were ignored or justified?",
        "What borders changed?",
        "What cultures disappeared?",
        "What technologies emerged?",
        "What trauma lingered?",
        "What propaganda shaped public memory?",
        "Which side controlled the historical narrative?",
        "What myths formed around the conflict?",
    ]),
    ("revolutions", "Revolutions & Social Change", [
        "What revolutions occurred?",
        "Why did they begin?",
        "Oppression?",
        "Poverty?",
        "Ideology?",
        "Hunger?",
        "Corruption?",
        "Religious persecution?",
        "What sparked public outrage?",
        "Who led the revolution?",
        "Intellectuals?",
        "Workers?",
        "Nobles?",
        "Soldiers?",
        "Prophets?",
        "Did the revolution succeed?",
        "What systems changed?",
        "Government?",
        "Religion?",
        "Economy?",
        "Class structure?",
        "Did things actually improve?",
        "Who benefited most?",
        "Who suffered?",
        "Did the revolution become oppressive itself?",
        "How is the revolution remembered today?",
        "Heroically?",
        "Tragically?",
        "Divisively?",
        "Is the official story accurate?",
        "What truths are hidden?",
    ]),
    ("religion", "Religion & Historical Influence", [
        "How did religion shape history?",
        "What religions rose and fell?",
        "Were there religious wars?",
        "Crusades?",
        "Purges?",
        "Holy empires?",
        "What prophets changed history?",
        "What miracles altered society?",
        "Were gods ever proven real?",
        "Did religion unify or divide civilizations?",
        "Did religious institutions hold political power?",
        "Were rulers divine?",
        "Were heretics persecuted?",
        "What sacred texts shaped law?",
        "What religious schisms split nations?",
        "What forbidden beliefs survived underground?",
    ]),
    ("magicHist", "Magic & Historical Development", [
        "Has magic always existed?",
        "When was it discovered?",
        "Who controlled it?",
        "Did magic create empires?",
        "Did magic destroy civilizations?",
        "Were magical disasters historical turning points?",
        "Were magical users worshipped?",
        "Feared?",
        "Enslaved?",
        "Regulated?",
        "Did magical knowledge rise and decline?",
        "Was there a magical golden age?",
        "What magical technologies were lost?",
        "What magical wars occurred?",
        "What magical catastrophe changed history forever?",
    ]),
    ("technology", "Technology & Progress", [
        "What inventions changed history?",
        "Writing?",
        "Printing?",
        "Gunpowder?",
        "Airships?",
        "Steam engines?",
        "AI?",
        "Teleportation?",
        "Magical engineering?",
        "What invention spread ideas fastest?",
        "What invention made empires possible?",
        "Was progress rapid or slow?",
        "What societies resisted innovation?",
        "What societies embraced it?",
        "What technologies were suppressed?",
        "Who controlled technological knowledge?",
        "Did technology create inequality?",
    ]),
    ("exploration", "Exploration & Discovery", [
        "What lands were unexplored?",
        "Why?",
        "Fear?",
        "Distance?",
        "Monsters?",
        "Politics?",
        "Weather?",
        "What explorers became legends?",
        "What discoveries changed history?",
        "What civilizations were discovered unfairly?",
        "Which societies colonized others?",
        "Why?",
        "Resources?",
        "Religion?",
        "Expansion?",
        "Survival?",
        "What damage did colonization cause?",
        "What cultures survived assimilation?",
        "What resistance movements formed?",
    ]),
    ("figures", "Historical Figures", [
        "Who were the greatest rulers?",
        "Why are they remembered?",
        "What made them effective?",
        "Cruel?",
        "Brilliant?",
        "Charismatic?",
        "What personal flaws shaped history?",
        "What rulers nearly destroyed civilization?",
        "What heroes became mythologized?",
        "Which villains were misunderstood?",
        "What historical figures vanished mysteriously?",
        "What figures are controversial today?",
        "Who was erased from official history?",
        "How much did individuals change history?",
        "Were events inevitable without them?",
        "What assassin altered everything?",
        "Inventor?",
        "Prophet?",
        "Conqueror?",
    ]),
    ("mysteries", "Historical Mysteries", [
        "What historical mysteries remain unsolved?",
        "Lost cities?",
        "Missing rulers?",
        "Ancient weapons?",
        "Forgotten languages?",
        "Hidden civilizations?",
        "What event has contradictory records?",
        "What ruins defy explanation?",
        "What conspiracy theories exist historically?",
        "What truths were hidden intentionally?",
        "Who erased records?",
        "Why?",
        "Political survival?",
        "Religious doctrine?",
        "National pride?",
        "Fear?",
        "What archives are forbidden?",
    ]),
    ("trauma", "Historical Trauma & Collective Memory", [
        "What events traumatized entire cultures?",
        "Genocide?",
        "Slavery?",
        "Plagues?",
        "Occupation?",
        "Magical disasters?",
        "What fears still exist because of history?",
        "What traditions emerged from survival?",
        "How do societies remember tragedy?",
        "Memorials?",
        "Holidays?",
        "Silence?",
        "Propaganda?",
        "Denial?",
        "Who benefits from historical forgetting?",
        "Who fights to preserve memory?",
    ]),
    ("dailyLife", "Daily Life Through History", [
        "What was life like for common people during each era?",
        "What did people eat?",
        "Wear?",
        "Fear?",
        "Dream about?",
        "How did peasants differ from nobles?",
        "How did city life differ from rural life?",
        "What rights existed?",
        "What injustices were normal?",
        "How did marriage evolve?",
        "Gender roles?",
        "Education?",
        "Parenting?",
        "Labor?",
        "Religion?",
        "Entertainment?",
        "Disease?",
        "Hygiene?",
        "How did these change historically?",
    ]),
    ("economy", "Economy & Historical Wealth", [
        "What resources created wealth?",
        "Gold?",
        "Spices?",
        "Oil?",
        "Mana?",
        "Slaves?",
        "Knowledge?",
        "What trade routes shaped history?",
        "Which cities became economic powers?",
        "What caused economic collapse?",
        "How severe was inequality historically?",
        "What systems exploited workers?",
        "Serfdom?",
        "Slavery?",
        "Debt?",
        "Corporations?",
        "Imperial extraction?",
        "What uprisings resulted?",
    ]),
    ("culture", "Historical Culture & Identity", [
        "How did languages evolve?",
        "What cultures blended together?",
        "What traditions survived conquest?",
        "What customs disappeared?",
        "What foods spread globally?",
        "What cultural exchanges changed history?",
        "What myths unify nations?",
        "What invented traditions exist?",
        "What stories are taught in schools?",
        "What historical lies became patriotic truth?",
    ]),
    ("knowledge", "Science, Knowledge & Philosophy", [
        "Who preserved knowledge?",
        "Monks?",
        "Scholars?",
        "Machines?",
        "Archives?",
        "Oral tradition?",
        "What knowledge was lost?",
        "Burned?",
        "Forbidden?",
        "What discoveries threatened power structures?",
        "What philosophies dominated different eras?",
        "What thinkers reshaped civilization?",
        "What moral systems justified conquest?",
        "Peace?",
        "Slavery?",
        "Revolution?",
        "Progress?",
    ]),
    ("environment", "Historical Environment & Disaster", [
        "Did climate shape history?",
        "Ice ages?",
        "Droughts?",
        "Floods?",
        "Volcanic winters?",
        "Magical storms?",
        "What civilizations collapsed environmentally?",
        "What diseases changed history?",
        "How did societies react?",
        "Panic?",
        "Science?",
        "Religion?",
        "Violence?",
        "What cures were discovered?",
        "What prejudice resulted from epidemics?",
    ]),
    ("hidden", "Hidden History & Secret Powers", [
        "Did secret societies shape history?",
        "Assassins?",
        "Cults?",
        "Ancient immortals?",
        "Dragons?",
        "Corporations?",
        "Hidden gods?",
        "What wars were manipulated secretly?",
        "What rulers were puppets?",
        "What truths would destabilize society if revealed?",
        "What ancient power is hidden?",
        "What civilization should not have existed?",
        "What historical event was staged?",
    ]),
    ("legacy", "The Present & Historical Legacy", [
        "How does history affect the modern world?",
        "What borders still cause conflict?",
        "What historical hatred survives?",
        "What traditions endure?",
        "What ruins still matter politically?",
        "What empire's legacy dominates today?",
        "Who controls historical education?",
        "What historical debates divide society?",
        "What history is politicized?",
        "What history is romanticized?",
        "What history is censored?",
    ]),
    ("meta", "Meta-History", [
        "What historical event is misunderstood by most people?",
        "What historical figure became larger than life unfairly?",
        "What barbarian culture was actually sophisticated?",
        "What civilization thought itself eternal?",
        "What empire fell faster than anyone expected?",
        "What prophecy altered political decisions?",
        "What event split history into before and after?",
        "What historical lesson was ignored repeatedly?",
        "What event changed language forever?",
        "What historical site attracts pilgrims?",
        "Tourists?",
        "Scholars?",
        "Grave robbers?",
        "What ancient fear still shapes modern politics?",
        "What historical trauma became cultural identity?",
    ]),
]

for i, (sid, title, qs) in enumerate(SECTIONS_RAW):
    SECTIONS_RAW[i] = (sid, title, GLYPHS.get(sid, "◆"), qs)

INTRO = (
    "Trace your world's past — from first fires and founding myths through empires, revolutions, and the scars that still shape the present. "
    "Create a separate chronicle for each realm, era, or timeline you need."
)

def js_str(s):
    return json.dumps(s, ensure_ascii=False)

lines = [
    "/** Auto-generated history codex sections. */",
    "",
    f"export const HISTORY_INTRO = {js_str(INTRO)};",
    "",
    "export const HISTORY_SECTIONS = [",
]
for sid, title, glyph, qs in SECTIONS_RAW:
    lines.append("    {")
    lines.append(f"        id: {js_str(sid)},")
    lines.append(f"        title: {js_str(title)},")
    lines.append(f"        glyph: {js_str(glyph)},")
    lines.append("        questions: [")
    for key, text in qlist(sid, qs):
        lines.append(f"            [{js_str(key)}, {js_str(text)}],")
    lines.append("        ]")
    lines.append("    },")
lines.append("];")
lines.append("")

out = Path(__file__).resolve().parent.parent / "js" / "history-sections.js"
out.write_text("\n".join(lines), encoding="utf-8")
total = sum(len(q) for _, _, _, q in SECTIONS_RAW)
print(f"Wrote {out} — {len(SECTIONS_RAW)} sections, {total} questions")
