# Generates js/geography-sections.js
import json
from pathlib import Path

def qlist(section_id, questions):
    return [[f"{section_id}_{i}", text] for i, text in enumerate(questions)]

GLYPHS = {
    "cosmic": "✧", "continents": "◇", "mountains": "⛰", "oceans": "≈",
    "climate": "☁", "forests": "❧", "deserts": "△", "ecology": "❋",
    "resources": "⛏", "settlements": "⌂", "borders": "⚑", "travel": "🧭",
    "infrastructure": "⊞", "sacred": "☽", "disasters": "⚡", "cultural": "◎",
    "warfare": "⚔", "economy": "⚖", "magicGeo": "✦", "identity": "✒",
}

SECTIONS_RAW = [
    ("cosmic", "Planetary & Cosmic Foundations", [
        "What is the name of the planet or world?",
        "Who named it?",
        "What do different cultures call it?",
        "Is the world a planet, realm, dimension, moon, artificial construct, flat world, hollow world, living entity, or something stranger?",
        "How large is it compared to Earth?",
        "How many moons does it have?",
        "Do the moons affect tides, magic, fertility, weather, monsters, or religion?",
        "What color is the sky?",
        "Does the sky change seasonally or magically?",
        "What stars, constellations, or celestial events matter culturally?",
        "Are there visible neighboring planets or realms?",
        "Does the world orbit a sun?",
        "Multiple suns?",
        "A dying star?",
        "A magical source?",
        "Is the planet geologically active?",
        "Is the world naturally stable?",
        "Is reality itself unstable in certain areas?",
        "Does geography connect to religion or mythology?",
        "Are mountains believed to hold gods?",
        "Are oceans believed endless?",
        "Are there sacred directions?",
        "Are certain regions believed cursed, holy, forbidden, or unreal?",
        "Are there areas where physical laws behave differently?",
        "Does magic shape geography?",
        "Did gods, titans, dragons, or ancient civilizations physically shape the land?",
    ]),
    ("continents", "Continents & Major Regions", [
        "How many continents or major landmasses exist?",
        "Are continents politically unified or fragmented?",
        "Which continent is oldest?",
        "Which is youngest?",
        "Which is most explored?",
        "Which is mysterious or inaccessible?",
        "What regions are densely populated?",
        "What regions remain wild?",
        "What regions are deadly to survive in?",
        "Are continents drifting?",
        "Are there lost continents or submerged lands?",
        "Are there floating continents or underground worlds?",
        "What defines each major region — climate, terrain, culture, resources, wildlife, religion, or political power?",
        "What stereotypes exist about each region?",
        "Which region dominates globally?",
        "Which region is exploited?",
        "Which region is isolated?",
        "Which region is contested?",
    ]),
    ("mountains", "Mountains & Geological Features", [
        "Where are the major mountain ranges?",
        "How were they formed?",
        "Are they volcanic, tectonic, magical, divine, or artificial?",
        "What cultures live within them?",
        "What resources come from them?",
        "What dangers exist there?",
        "Are mountains considered barriers, homes, fortresses, sacred places, or prisons?",
        "Which peaks are unclimbed?",
        "Which peaks are sacred?",
        "Which peaks are feared?",
        "What creatures inhabit them?",
        "Are there hidden cities, ruins, monasteries, mines, or kingdoms inside mountains?",
        "Are earthquakes common?",
        "Are volcanoes active?",
        "Are there geysers, crystal caverns, lava fields, obsidian deserts, petrified forests, sinkholes, canyons, fault lines, or magical scars?",
        "Are there supernatural geological phenomena?",
        "What regions are unstable?",
        "What natural disasters shape civilization?",
        "How do people predict geological disasters?",
        "Are there legendary disasters tied to geography?",
    ]),
    ("oceans", "Oceans, Seas & Waterways", [
        "How many oceans exist?",
        "Are oceans fully explored?",
        "What lies beneath them?",
        "Are there underwater civilizations?",
        "Are sea monsters real?",
        "Are oceans barriers or highways?",
        "Which ocean is most dangerous?",
        "Which ocean is most economically important?",
        "What myths surround the seas?",
        "Are there cursed waters?",
        "Are there regions where ships vanish?",
        "What are the major rivers?",
        "Which civilizations formed around them?",
        "What rivers are sacred?",
        "Which rivers flood seasonally?",
        "What rivers divide nations?",
        "Which lakes are famous?",
        "Are lakes freshwater, saltwater, acidic, magical, frozen, or alive?",
        "Are rivers navigable?",
        "What trade depends on waterways?",
        "Are there underground rivers?",
        "Floating rivers?",
        "Rivers of magical energy?",
        "Are coastlines stable or constantly changing?",
        "Are there cliffs, fjords, marshes, coral reefs, mangroves, black sand beaches, or shattered archipelagos?",
        "What coastal areas are wealthy?",
        "Which are pirate-controlled?",
        "What creatures inhabit coastal waters?",
        "How do coastal cultures differ from inland ones?",
    ]),
    ("climate", "Climate & Weather", [
        "What climate zones exist — tropical, arid, temperate, polar, magical?",
        "Are climates realistic or altered by supernatural forces?",
        "Which regions are fertile?",
        "Which are barren?",
        "What regions are hardest to survive in?",
        "How many seasons exist?",
        "Are seasons regular?",
        "What events mark seasonal change?",
        "Are there magical seasons?",
        "Long winters?",
        "Endless summers?",
        "Deadly storm periods?",
        "Eclipse seasons?",
        "Does climate affect culture, warfare, migration, religion, or politics?",
        "What weather patterns dominate the world?",
        "Are storms common?",
        "What regions experience hurricanes, monsoons, blizzards, droughts, acid rain, magical storms, fire rain, or ashfall?",
        "Can weather be controlled?",
        "What weather phenomena inspire myths?",
        "What weather is considered sacred or cursed?",
        "How do people predict weather?",
        "What weather kills the most people?",
    ]),
    ("forests", "Forests, Jungles & Wilderness", [
        "What types of forests exist — ancient, mushroom, crystal, petrified, haunted?",
        "What lives there?",
        "Who controls them?",
        "Are forests exploited or protected?",
        "What resources come from forests?",
        "Are forests expanding or shrinking?",
        "Are there sentient forests?",
        "What secrets are hidden there?",
        "What makes the wild dangerous — disease, predators, magic, terrain, or isolation?",
        "What ruins exist deep in wilderness?",
        "What civilizations disappeared there?",
        "What explorers became legends?",
        "What wilderness areas remain unmapped?",
        "Why?",
    ]),
    ("deserts", "Deserts & Harsh Environments", [
        "What caused the desert — climate, magic, war, or catastrophe?",
        "What kinds of deserts exist — sand, ice, salt, ash, glass, or stone?",
        "What survives there?",
        "How do people travel through deserts?",
        "What settlements exist there?",
        "What resources make deserts valuable?",
        "What myths exist about them?",
        "What is the deadliest environment in the world?",
        "What creatures dominate these regions?",
        "What civilizations adapted to them?",
        "What technology or magic allows survival?",
        "What resources justify the danger?",
    ]),
    ("ecology", "Flora, Fauna & Ecology", [
        "How do ecosystems function?",
        "Are food chains realistic or magical?",
        "What apex predators exist?",
        "What invasive species threaten regions?",
        "What creatures are domesticated?",
        "What creatures are sacred?",
        "What creatures are hunted to extinction?",
        "What environmental imbalance exists?",
        "What plants are culturally important?",
        "What plants are medicinal, poisonous, religious, magical, or addictive?",
        "What crops sustain civilizations?",
        "What regions cannot support agriculture?",
        "Are there giant plants, carnivorous plants, or sentient plants?",
        "What animals dominate each region?",
        "Which animals are feared, revered, hunted, or used for war, transport, labor, companionship, or religion?",
        "What legendary creatures shape local culture?",
    ]),
    ("resources", "Natural Resources & Wealth", [
        "What resources exist naturally — metals, oil, mana crystals, rare woods, ruins, monster remains, fertile soil?",
        "What regions are resource-rich?",
        "Which are poor?",
        "What wars are fought over resources?",
        "What resource created empires?",
        "What resource caused collapse?",
        "How are resources gathered — mining, farming, hunting, harvesting, magical extraction?",
        "What environmental damage exists?",
        "What labor systems support extraction — slavery, guilds, corporations, state control?",
        "What regions are exploited colonies?",
    ]),
    ("settlements", "Settlements & Human Geography", [
        "Why were cities built where they are — defense, trade, water, religion, resources, magic, or ruins?",
        "What areas remain unsettled?",
        "Why?",
        "How far apart are settlements?",
        "What connects them?",
        "What is life like outside cities?",
        "Are villages isolated or interconnected?",
        "What dangers threaten rural life — raiders, monsters, weather, disease, or spirits?",
        "What traditions survive in remote places?",
        "How do cities interact with geography — vertical, underground, floating, sprawling, fortified, aquatic, layered, or carved?",
        "How does geography shape architecture?",
        "What cities are naturally protected?",
        "What cities are vulnerable?",
    ]),
    ("borders", "Borders, Territories & Political Geography", [
        "How are borders defined — rivers, mountains, walls, magic barriers, treaties, ethnic divisions, or military zones?",
        "Are borders stable?",
        "What regions are disputed?",
        "What borders are impossible to enforce?",
        "What regions change hands often?",
        "What regions want independence?",
        "What regions were conquered recently?",
        "What geographic feature protects major powers?",
        "What geographic weakness threatens them?",
        "Which regions are strategically vital?",
        "Why?",
    ]),
    ("travel", "Travel, Exploration & Distance", [
        "How do people travel — roads, rivers, sea, airships, mounts, teleportation, or portals?",
        "What regions are hardest to reach?",
        "Why?",
        "What routes are famous, dangerous, sacred, or profitable?",
        "What regions remain unexplored — why monsters, weather, politics, reality distortion, or isolation?",
        "What famous explorers exist?",
        "What maps are inaccurate?",
        "What ruins attract adventurers?",
        "What myths drive exploration?",
    ]),
    ("infrastructure", "Infrastructure & Development", [
        "Who builds roads?",
        "Who maintains them?",
        "What regions lack infrastructure?",
        "How does terrain affect transportation?",
        "Are roads safe, guarded, or haunted?",
        "What trade routes matter most?",
        "What geographic engineering exists — dams, aqueducts, floating bridges, tunnels, terraforming, weather control, magical reshaping?",
        "What massive construction projects changed geography forever?",
    ]),
    ("sacred", "Sacred & Mythical Geography", [
        "What locations are holy?",
        "Why?",
        "Who controls them?",
        "What pilgrimages exist?",
        "What miracles supposedly happened there?",
        "What locations are forbidden, cursed, lost, or protected?",
        "Are there gateways to other realms?",
        "Sleeping gods beneath mountains?",
        "Bottomless oceans or endless storms?",
        "Living islands, moving deserts, or reality fractures?",
        "Time-distorted regions?",
        "Places where the dead gather?",
        "Locations erased from maps?",
    ]),
    ("disasters", "Disasters & Environmental Threats", [
        "What disasters occur regularly — floods, wildfires, earthquakes, blizzards, sandstorms, magical catastrophes?",
        "What regions are disaster-prone?",
        "How do societies prepare?",
        "Is the environment healthy?",
        "What ecosystems are dying?",
        "What caused environmental decline — industry, magic, war, climate change, or divine punishment?",
        "What resources are running out?",
        "What regions are becoming uninhabitable?",
    ]),
    ("cultural", "Cultural Geography", [
        "How does terrain shape culture?",
        "How do mountain people differ from plains people, coastal from inland, desert from forest?",
        "What stereotypes exist between regions?",
        "What regional rivalries exist?",
        "What accents, languages, or foods vary by region?",
        "What traditions come from geography?",
        "Which regions developed separately?",
        "Which regions became crossroads?",
        "What isolated communities evolved uniquely?",
        "Which areas are culturally blended?",
    ]),
    ("warfare", "Warfare & Strategic Geography", [
        "What terrain is hardest to conquer?",
        "What regions serve as natural defenses?",
        "What chokepoints matter most — mountain passes, rivers, ports, or valleys?",
        "What terrain favors guerrilla warfare, cavalry, naval warfare, or magic warfare?",
        "Where are castles and forts built?",
        "What cities are considered unconquerable?",
        "What terrain makes invasion impossible?",
        "What famous battles were decided by geography?",
    ]),
    ("economy", "Economy & Geographic Influence", [
        "What regions control trade?",
        "What trade routes are essential?",
        "What regions became rich due to location alone?",
        "What geographic feature made an empire possible?",
        "Which cities became ports, crossroads, mining hubs, pilgrimage sites, or fortress capitals?",
        "What areas remain poor because of geography?",
        "Which regions cannot easily industrialize?",
        "Which regions rely heavily on imports?",
    ]),
    ("magicGeo", "Magic & Geography", [
        "Does magic affect terrain?",
        "Are there mana-rich regions or dead magic zones?",
        "Corrupted lands, floating islands, living mountains, weather anomalies, time fractures, or magical ecosystems?",
        "Where does magical energy come from?",
        "Is it mined, harvested, seasonal, or dangerous?",
        "Who controls it?",
        "What wars have been fought over magical geography?",
    ]),
    ("identity", "Geographic Identity Questions", [
        "What location do people fear most?",
        "What place is considered the heart of civilization?",
        "What place symbolizes death or exile?",
        "What region is romanticized unfairly?",
        "What place do stories exaggerate?",
        "What location do children dream of visiting?",
        "What region do maps avoid?",
        "What geographic feature appears in songs and legends constantly?",
        "What journey is considered a rite of passage?",
        "What route changes a traveler forever?",
    ]),
]

for i, (sid, title, qs) in enumerate(SECTIONS_RAW):
    SECTIONS_RAW[i] = (sid, title, GLYPHS.get(sid, "◆"), qs)

INTRO = (
    "Map your world's bones — from sky and seas to climate, wilds, borders, and the routes that bind them. "
    "Create a separate geography for each planet, continent, or realm you need."
)

def js_str(s):
    return json.dumps(s, ensure_ascii=False)

lines = [
    "/** Auto-generated geography & terrain codex sections. */",
    "",
    f"export const GEOGRAPHY_INTRO = {js_str(INTRO)};",
    "",
    "export const GEOGRAPHY_SECTIONS = [",
]
for sid, title, glyph, qs in SECTIONS_RAW:
    lines.append("    {")
    lines.append(f"        id: {js_str(sid)},")
    lines.append(f"        title: {js_str(title)},")
    lines.append(f"        glyph: {js_str(glyph)},")
    lines.append("        questions: [")
    for key, text in qlist(sid, qs):
        lines.append(f"            [{js_str(key)}, {js_str(text)}],")
    lines.append("        ]")
    lines.append("    },")
lines.append("];")
lines.append("")

out = Path(__file__).resolve().parent.parent / "js" / "geography-sections.js"
out.write_text("\n".join(lines), encoding="utf-8")
total = sum(len(q) for _, _, _, q in SECTIONS_RAW)
print(f"Wrote {out} — {len(SECTIONS_RAW)} sections, {total} questions")
