# Generates js/peoples-culture-sections.js
import json
from pathlib import Path

def qlist(section_id, questions):
    return [[f"{section_id}_{i}", text] for i, text in enumerate(questions)]

SECTIONS_RAW = [
    ("core", "Core Identity", "◉", [
        "What is this people, culture, species, tribe, nation, or civilization called?",
        "What do they call themselves?",
        "What do outsiders call them?",
        "Is the outside name respectful, outdated, insulting, or misunderstood?",
        "Are there multiple names depending on region, language, class, or history?",
        "What does their name mean?",
        "Who gave them that name?",
        "How old is this culture or species?",
        "Are they ancient, emerging, declining, hidden, displaced, or reborn?",
        "What is the first thing outsiders usually notice about them?",
        "What is the first thing they want outsiders to notice?",
        "What is the biggest misconception about them?",
        "What truth about them would surprise outsiders?",
    ]),
    ("origins", "Origins & History", "☍", [
        "Where did they come from?",
        "Do they have a scientific, mythological, religious, or magical origin?",
        "Were they created, evolved, chosen, cursed, engineered, summoned, or transformed?",
        "Do they believe their own origin story literally?",
        "Are there competing origin stories?",
        "Who benefits from the dominant version of their history?",
        "What part of their origin has been erased or hidden?",
        "What ancient event shaped them most?",
        "What do their oldest records say?",
        "What do their oldest myths say?",
        "What do their enemies say about their beginnings?",
        "What physical evidence supports or contradicts their history?",
        "What are the major eras of their history?",
        "What event marks Year One for them?",
        "What wars, migrations, plagues, miracles, disasters, or discoveries changed them?",
        "What was their golden age?",
        "What caused their decline, if any?",
        "What historical trauma still affects them?",
        "What victory are they proudest of?",
        "What defeat are they ashamed of?",
        "What historical figure is most revered?",
        "What historical figure is most hated?",
        "What history is taught to children?",
        "What history is only taught to elites?",
        "What history is forbidden?",
    ]),
    ("biology", "Biology & Physical Traits", "❋", [
        "What do they look like?",
        "What traits distinguish them from humans or neighboring peoples?",
        "What range of height, build, coloring, markings, or features exists?",
        "Are there regional physical variations?",
        "Are there class-based or caste-based physical modifications?",
        "Are certain traits considered beautiful, ugly, holy, unlucky, or dangerous?",
        "Do they have horns, tails, wings, scales, fur, feathers, gills, claws, extra limbs, unusual eyes, or other features?",
        "Are these traits functional, decorative, symbolic, or vestigial?",
        "How do they move?",
        "Are they built for running, climbing, swimming, flying, burrowing, stealth, endurance, or strength?",
        "Which senses are strongest?",
        "Do they see colors humans cannot?",
        "Can they detect heat, magic, emotions, electricity, scent trails, pressure, spirits, or magnetic fields?",
        "Which sense do they rely on most?",
        "What overwhelms their senses?",
        "What environments are uncomfortable or dangerous for them?",
        "How does their sensory world shape their art, language, architecture, or warfare?",
        "How are they born, hatched, grown, created, awakened, or formed?",
        "How long do they live?",
        "How quickly do they mature?",
        "What are their life stages?",
        "Are children physically different from adults?",
        "Are elders physically or magically different?",
        "Is aging feared, honored, hidden, or celebrated?",
        "Can they die of old age?",
        "What usually kills them?",
        "Do they regenerate, shed, molt, transform, reincarnate, or metamorphose?",
        "Are there seasonal biological changes?",
        "Do they hibernate, migrate, bloom, rut, molt, or enter dormancy?",
    ]),
    ("family", "Family & Kinship", "⌂", [
        "What counts as family?",
        "Is family based on blood, marriage, adoption, oath, clan, household, reincarnation, magic, profession, or shared survival?",
        "Are families nuclear, extended, communal, matriarchal, patriarchal, elder-led, child-led, or fluid?",
        "Who raises children?",
        "Are children raised by parents, clans, schools, temples, guilds, villages, the state, spirits, or machines?",
        "Are siblings important?",
        "Are birth order, twins, or only children given special meaning?",
        "Are ancestors considered part of the family?",
        "Can someone be removed from a family?",
        "Can someone choose a new family?",
        "Do they marry?",
        "What forms of partnership exist?",
        "Is marriage romantic, political, economic, spiritual, reproductive, military, or magical?",
        "Who chooses partners?",
        "Are arranged marriages common?",
        "Are love matches respected?",
        "Can people have multiple spouses or partners?",
        "Are partnerships temporary, lifelong, seasonal, contractual, or reincarnated?",
        "What makes a marriage legal?",
        "What makes it sacred?",
        "How does divorce work?",
        "What happens to property, children, titles, debts, or magic bonds after separation?",
    ]),
    ("society", "Society, Class & Power", "⚖", [
        "How is society organized?",
        "Are there classes, castes, clans, tribes, guilds, houses, orders, ranks, bloodlines, or species divisions?",
        "Can people move between classes?",
        "What determines status?",
        "Is status based on birth, wealth, age, magic, military skill, education, beauty, ancestry, piety, fertility, conquest, or service?",
        "Who has the most power?",
        "Who has the least?",
        "Who is invisible in society?",
        "Who is protected?",
        "Who is exploited?",
        "What privileges do elites have?",
        "What obligations do elites have?",
        "What resentment exists between groups?",
        "Who rules them?",
        "Is leadership inherited, elected, conquered, appointed, divinely chosen, magically proven, or earned through trial?",
        "Can leaders be removed?",
        "What makes a ruler legitimate?",
        "What makes a ruler hated?",
        "Are leaders expected to be warriors, scholars, priests, judges, parents, prophets, or symbols?",
        "How close are leaders to ordinary people?",
        "What checks their power?",
        "What happens during a succession crisis?",
    ]),
    ("government", "Government, Law & Justice", "⚔", [
        "What political system do they use?",
        "Is it monarchy, empire, republic, theocracy, council, clan confederation, dictatorship, anarchic network, hive mind, AI governance, magical contract, or something else?",
        "Is government centralized or local?",
        "What institutions exist?",
        "How are laws created?",
        "Who enforces them?",
        "Who interprets them?",
        "Are laws written, oral, sung, carved, magically bound, or remembered by specialists?",
        "Are there different laws for different classes, genders, species, or outsiders?",
        "What is considered a crime?",
        "What is considered unforgivable?",
        "What crimes are tolerated if committed by elites?",
        "What crimes are punished harshly among the poor?",
        "Are punishments physical, financial, social, magical, spiritual, psychological, or exile-based?",
        "Do they use prisons?",
        "Is justice focused on punishment, revenge, restoration, purification, deterrence, or balance?",
        "Are trials public or private?",
        "Can the accused defend themselves?",
        "Can magic, divination, memory-reading, or oath-binding be used as evidence?",
        "What happens when the law is wrong?",
    ]),
    ("language", "Language & Communication", "✎", [
        "What language or languages do they speak?",
        "Is their language spoken, signed, sung, telepathic, scent-based, color-based, movement-based, written, carved, knotted, magical, or symbolic?",
        "How old is the language?",
        "Has it changed over time?",
        "Are there dialects?",
        "Are dialects tied to class, region, age, gender, profession, or religion?",
        "What words do they have that outsiders struggle to translate?",
        "What concepts do they lack words for?",
        "What sounds are difficult for outsiders to pronounce?",
        "What does a formal greeting sound like?",
        "What does an intimate greeting sound like?",
        "What insults are especially severe?",
        "What compliments matter most?",
        "What gestures are polite?",
        "What gestures are rude?",
        "How much eye contact is normal?",
        "Is touching normal?",
        "Do they bow, kneel, salute, bare teeth, lower wings, expose palms, change color, exchange scent, or share breath?",
        "How do they show anger?",
        "How do they show affection?",
        "How do they show grief?",
        "How do they show submission or respect?",
        "What body language do outsiders often misread?",
    ]),
    ("religion", "Religion & Spirituality", "☽", [
        "What do they believe about the universe?",
        "Do they worship gods, ancestors, spirits, nature, stars, dragons, saints, machines, abstract principles, or nothing?",
        "Are their beliefs organized or personal?",
        "Is religion mandatory?",
        "Are there atheists, skeptics, heretics, reformers, or hidden believers?",
        "What do they believe happens after death?",
        "Do they believe souls exist?",
        "Can souls be damaged, stolen, reborn, judged, consumed, or divided?",
        "What is sacred?",
        "What is profane?",
        "What is taboo?",
        "Where do they worship?",
        "Who leads rituals?",
        "Are priests powerful?",
        "Are religious leaders separate from political leaders?",
        "What offerings are made?",
        "What prayers are common?",
        "What holidays are sacred?",
        "Are sacrifices symbolic, animal, human, magical, emotional, or material?",
        "What religious duty does every person have?",
        "What religious duty is reserved for specialists?",
        "What happens to someone who breaks sacred law?",
    ]),
    ("values", "Values & Worldview", "◇", [
        "What virtues do they admire most?",
        "What flaws do they despise most?",
        "Do they value honor, freedom, loyalty, beauty, courage, obedience, knowledge, survival, harmony, conquest, humility, ambition, sacrifice, or truth?",
        "Which value matters more: family or self?",
        "Law or mercy?",
        "Truth or peace?",
        "Tradition or innovation?",
        "Individuality or unity?",
        "Strength or compassion?",
        "Are their values changing between generations?",
        "What do they consider good?",
        "What do they consider evil?",
        "Is morality absolute, situational, religious, legal, ancestral, or practical?",
        "What behavior is normal to them but horrifying to outsiders?",
        "What outsider behavior disgusts them?",
        "What moral contradiction exists in their society?",
        "What hypocrisy do they refuse to acknowledge?",
        'What would a "good person" look like in this culture?',
        'What would a "bad person" look like?',
    ]),
    ("daily", "Daily Life", "☀", [
        "What does an ordinary home look like?",
        "Who lives together?",
        "What materials are homes made from?",
        "Are homes permanent, mobile, underground, underwater, vertical, communal, magical, alive, or temporary?",
        "What rooms are considered essential?",
        "What is private?",
        "What is shared?",
        "How are homes heated, cooled, lit, defended, or blessed?",
        "What smells, sounds, and textures define daily life?",
        "What does a normal day look like?",
        "When do they wake and sleep?",
        "Do they follow the sun, moons, tides, seasons, bells, prayers, work shifts, stars, or biological cycles?",
        "What do children do all day?",
        "What do elders do?",
        "What do workers do?",
        "When do people rest?",
        "What do they do for fun?",
        "What daily task is considered sacred, annoying, dangerous, or shameful?",
    ]),
    ("food", "Food & Survival", "🜃", [
        "What do they eat?",
        "Are they omnivores, carnivores, herbivores, photosynthetic, mineral-eaters, blood-drinkers, energy-feeders, or something stranger?",
        "What foods are staples?",
        "What foods are luxury items?",
        "What foods are taboo?",
        "What foods are served at birth, marriage, funerals, victory, mourning, or religious festivals?",
        "Do they cook with fire, fermentation, magic, pressure, sunlight, acid, smoke, ice, or raw preparation?",
        "What spices, herbs, or flavors dominate?",
        "What textures do they enjoy?",
        "What foods do outsiders find disgusting?",
        "What outsider foods are poisonous to them?",
        "Do they eat alone or communally?",
        "Who eats first?",
        "Are meals formal or casual?",
        "What utensils do they use?",
        "Do they use hands, claws, chopsticks, blades, shells, straws, magic, or no utensils?",
        "Are there table manners?",
        "Is refusing food rude?",
        "Is sharing food intimate?",
        "Are feasts political?",
        "Are fasts spiritual?",
    ]),
    ("clothing", "Clothing & Adornment", "✧", [
        "What do they wear daily?",
        "What do they wear for war, worship, mourning, courtship, travel, work, or leadership?",
        "Is clothing practical, symbolic, modest, revealing, protective, magical, status-based, or artistic?",
        "What materials are used?",
        "Are fabrics woven, grown, shed, mined, enchanted, printed, carved, or alive?",
        "What colors are common?",
        "What colors are restricted?",
        "What patterns have meaning?",
        "What clothing is forbidden?",
        "What is considered beautiful?",
        "What is considered unattractive?",
        "Are tattoos, scars, piercings, brands, dyes, perfumes, implants, masks, hairstyles, horn carvings, scale polishing, feather braiding, or magical marks common?",
        "Are modifications voluntary or required?",
        "Do they mark age, status, marriage, crimes, achievements, grief, or faith?",
        "What beauty practice is painful?",
        "What beauty standard is harmful?",
        "What style is rebellious?",
    ]),
    ("education", "Education & Knowledge", "📜", [
        "How are children educated?",
        "Is education universal or restricted?",
        "Who teaches?",
        "What subjects matter most?",
        "Is literacy common?",
        "Are oral traditions valued more than books?",
        "Are memories stored magically or technologically?",
        "What knowledge is forbidden?",
        "What knowledge is sacred?",
        "What knowledge is gendered, classed, or profession-specific?",
        "How are apprenticeships handled?",
        "What must someone learn to be considered an adult?",
        "What do scholars study?",
        "What sciences exist?",
        "What do they misunderstand about the world?",
        "What do they understand better than others?",
        "Are historians trusted?",
        "Are philosophers respected?",
        "Are inventors celebrated or feared?",
        "Are libraries public, private, hidden, living, burned, or sacred?",
    ]),
    ("work", "Work, Economy & Trade", "⚙", [
        "What jobs are common?",
        "What jobs are prestigious?",
        "What jobs are shameful?",
        "What jobs are dangerous?",
        "Who does unwanted labor?",
        "Is labor divided by class, caste, gender, age, species, magic, or ability?",
        "Are artisans respected?",
        "Are merchants trusted?",
        "Are soldiers admired?",
        "Are farmers powerful or overlooked?",
        "Can people choose their profession?",
        "What do they use as money?",
        "Do they use coins, barter, debt, favors, shells, crystals, blood, memories, spells, labor, or reputation?",
        "What resources do they control?",
        "What do they import?",
        "What do they export?",
        "Who becomes wealthy?",
        "How is poverty treated?",
        "Are taxes paid in money, goods, service, children, magic, or loyalty?",
        "What black markets exist?",
    ]),
    ("art", "Art, Music & Storytelling", "♫", [
        "What art forms do they value?",
        "Is art decorative, sacred, political, historical, magical, practical, or rebellious?",
        "What materials are used?",
        "Are artists respected?",
        "Are artists censored?",
        "What symbols appear often?",
        "What is considered bad taste?",
        "What art is forbidden?",
        "What masterpiece defines this culture?",
        "What does their music sound like?",
        "What instruments do they use?",
        "Do they sing, hum, drum, whistle, chant, dance, resonate, click, or communicate through rhythm?",
        "Is music communal or professional?",
        "What songs does every child know?",
        "What songs are sung in mourning?",
        "What songs are sung before battle?",
        "What performances are sacred?",
        "What stories are performed but never written?",
    ]),
    ("war", "War & Defense", "🛡", [
        "Do they go to war?",
        "What causes war?",
        "Are they aggressive, defensive, expansionist, isolationist, mercenary, pacifist, or retaliatory?",
        "What weapons do they use?",
        "Do they use magic, beasts, machines, poison, weather, disease, illusions, siegecraft, assassins, or diplomacy?",
        "Who is allowed to fight?",
        "Are soldiers professional, conscripted, enslaved, volunteer, noble, religious, or magically bound?",
        "What is considered honorable in war?",
        "What is considered monstrous?",
        "How are prisoners treated?",
        "How are veterans treated?",
        "What happens to the defeated?",
        "How are settlements defended?",
        "Do they use walls, hidden locations, tunnels, wards, armies, geography, alliances, monsters, storms, or misinformation?",
        "What are they most afraid of?",
        "What enemy shaped their military culture?",
        "What weapon changed their history?",
    ]),
    ("magicTech", "Magic, Powers & Technology", "✦", [
        "Can they use magic?",
        "Is magic common or rare?",
        "Is magic biological, learned, divine, technological, environmental, inherited, or forbidden?",
        "Who controls magical knowledge?",
        "What magical abilities are associated with this culture or species?",
        "What are magic users called?",
        "Are magic users leaders, servants, weapons, healers, criminals, priests, or outcasts?",
        "What price does magic demand?",
        "What magical taboo exists?",
        "How does magic shape daily life?",
        "What level of technology do they have?",
        "What have they invented?",
        "What technology do they refuse to use?",
        "What technology do they misunderstand?",
        "Do they combine magic and technology?",
        "What tools are found in every home?",
        "What invention changed their society?",
        "What technology gives them power over others?",
        "What technology are they dependent on?",
    ]),
    ("health", "Health, Medicine & Disability", "❤", [
        "What diseases affect them?",
        "What diseases are they immune to?",
        "What injuries are common?",
        "Who provides medical care?",
        "Is medicine scientific, herbal, magical, spiritual, surgical, communal, or experimental?",
        "Are healers trusted?",
        "What treatments are effective?",
        "What treatments are harmful but traditional?",
        "What is considered a healthy body?",
        "What is considered illness?",
        "How does society treat disability?",
        "Are disabled people supported, hidden, honored, exploited, pitied, cured, feared, or ignored?",
        "Are some disabilities considered gifts?",
        "Are accommodations common?",
        "Does magic or technology change disability access?",
        "What body or mind differences are misunderstood?",
        "What stigma exists?",
        "Who challenges that stigma?",
    ]),
    ("gender", "Gender & Identity", "⚧", [
        "How does this culture understand gender?",
        "How many gender roles or categories exist?",
        "Are roles biological, spiritual, social, magical, occupational, or chosen?",
        "Are expectations strict or flexible?",
        "How are children introduced to gender roles?",
        "Are there rites tied to gender?",
        "What clothing, speech, work, names, or rituals are gendered?",
        "Can people change roles?",
        "Are nonconforming people accepted, sacred, criminalized, invisible, or misunderstood?",
        "What makes someone a full member of society?",
        "Can outsiders become members?",
        "Can members be expelled?",
        "What identities matter most: clan, city, species, religion, profession, class, family, language, or personal achievement?",
        "How do people introduce themselves formally?",
        "What identity would someone hide for safety?",
    ]),
    ("outsiders", "Outsiders & Other Cultures", "🌐", [
        "How do they treat outsiders?",
        "Are foreigners welcomed, tolerated, studied, converted, exploited, enslaved, feared, or killed?",
        "What cultures are they allied with?",
        "What cultures are enemies?",
        "Who do they trade with?",
        "Who do they refuse to trade with?",
        "What stereotypes do they hold about others?",
        "What stereotypes do others hold about them?",
        "What do they borrow from other cultures?",
        "What do they refuse to adopt?",
        "Do they live outside their homeland?",
        "What happens to those raised away from the culture?",
        "Are diasporic communities accepted as authentic?",
        "What traditions survive migration?",
        "What traditions change?",
        "What do exiles miss most?",
        "What do outsiders who join the culture never fully understand?",
    ]),
    ("conflict", "Conflict & Change", "⚡", [
        "What divides them?",
        "Are there political factions, religious schisms, class conflicts, generational tensions, regional rivalries, reform movements, or hidden rebellions?",
        "What issue could start a civil war?",
        "What issue is everyone afraid to discuss?",
        "What tradition is being challenged?",
        "What reform is gaining support?",
        "What group wants the old ways restored?",
        "What group wants radical change?",
        "What scandal would shake society?",
        "Are they rising or declining?",
        "What threatens their survival?",
        "What could save them?",
        "What future do leaders promise?",
        "What future do young people want?",
        "What future do elders fear?",
        "What prophecy, prediction, or political plan shapes their expectations?",
        "What would happen if they disappeared?",
        "What would happen if they became dominant?",
    ]),
    ("character", "Character & Story Hooks", "✒", [
        "How does a person from this culture introduce themselves?",
        "What manners were they raised with?",
        "What habits would they carry into foreign lands?",
        "What food would make them homesick?",
        "What insult would deeply wound them?",
        "What compliment would mean everything?",
        "What taboo might they break accidentally?",
        "What foreign custom would confuse them?",
        "What belief would they struggle to question?",
        "What story did they grow up hearing?",
        "What lullaby, proverb, warning, or prayer do they remember?",
        "What duty do they feel they owe their family?",
        "What duty do they feel they owe their people?",
        "What shame do they carry from their culture?",
        "What pride do they carry?",
        "What tradition do they secretly hate?",
        "What tradition would they defend fiercely?",
        "What would make them feel like a traitor?",
        "What would make them feel truly at home?",
    ]),
]

INTRO = (
    "Build peoples, cultures, species, tribes, nations, and civilizations in extraordinary depth. "
    "Each group saves separately — create as many as your world needs."
)

def js_str(s):
    return json.dumps(s, ensure_ascii=False)

lines = [
    "/** Auto-generated peoples & culture codex sections. */",
    "",
    f"export const PEOPLES_CULTURE_INTRO = {js_str(INTRO)};",
    "",
    "/** @type {{ id: string, title: string, glyph: string, questions: [string, string][] }[]} */",
    "export const PEOPLES_CULTURE_SECTIONS = [",
]
for sid, title, glyph, qs in SECTIONS_RAW:
    lines.append("    {")
    lines.append(f"        id: {js_str(sid)},")
    lines.append(f"        title: {js_str(title)},")
    lines.append(f"        glyph: {js_str(glyph)},")
    lines.append("        questions: [")
    for key, text in qlist(sid, qs):
        lines.append(f"            [{js_str(key)}, {js_str(text)}],")
    lines.append("        ]")
    lines.append("    },")
lines.append("];")
lines.append("")

out = Path(__file__).resolve().parent.parent / "js" / "peoples-culture-sections.js"
out.write_text("\n".join(lines), encoding="utf-8")
total_q = sum(len(qs) for _, _, _, qs in SECTIONS_RAW)
print(f"Wrote {out} — {len(SECTIONS_RAW)} sections, {total_q} questions")
